// Automatically generated by ffigen. DO NOT EDIT.
// ignore_for_file: type=lint, unused_element, camel_case_types, non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: unused_import
@ffi.DefaultAsset('package:num_dart/num_dart')
library;

import 'dart:ffi' as ffi;

/// Natively sort a double precision float64 array in-place on the FFI heap.
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Double>, ffi.Int)>()
external void native_sort_double(ffi.Pointer<ffi.Double> array, int size);

/// Natively sort a single precision float32 array in-place.
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Float>, ffi.Int)>()
external void native_sort_float(ffi.Pointer<ffi.Float> array, int size);

/// Natively sort an int64 array in-place.
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.LongLong>, ffi.Int)>()
external void native_sort_int64(ffi.Pointer<ffi.LongLong> array, int size);

/// Natively sort an int32 array in-place.
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Int>, ffi.Int)>()
external void native_sort_int32(ffi.Pointer<ffi.Int> array, int size);
