// THIS FILE IS AUTOGENERATED BY `tool/regenerate_hashes.dart`. TO UPDATE, RUN:
//
//   dart tool/regenerate_hashes.dart <github release tag>
//

import 'package:code_assets/code_assets.dart';

/// GitHub repository hosting prebuilt release artifacts and SLSA provenance attestations.
const repository = 'sigurdm/scientific_dart';

/// Release tag for prebuilt `ndarray` binaries.
const version = 'artifacts-v0.0.2';

/// Canonical release artifact filename for `(os, arch)`.
String ndarrayArtifactName(OS os, Architecture arch) {
  final ext = switch (os) {
    OS.windows => 'dll',
    OS.macOS || OS.iOS => 'dylib',
    _ => 'so',
  };
  return 'ndarray-${os.name}-${arch.name}.$ext';
}

/// SHA-256 digests for prebuilt `ndarray` binaries indexed by `(OS, Architecture)`.
const fileHashes = <(OS, Architecture), String>{
  (OS.linux, Architecture.x64):
      'ed3b0f78477f5165d81b5cdb7dd6a63393c39c6625cdd42470917f51ff17f9bc',
  (OS.linux, Architecture.arm64):
      '000ee9ac1d2ee39cd0b94954703204d14c6331c1c713429d4b42fd9dabc954d3',
  (OS.macOS, Architecture.arm64):
      '1856c03411e083f2e489d98ac8df995b14b1213bd411d3f63333e048366d2c3b',
  (OS.macOS, Architecture.x64):
      '89d1c215bda8843be8339d5eb98d6601be0f15337e773c62608821d8c88e917e',
  (OS.windows, Architecture.x64):
      'a59697e50d5c6b54f1cc357c11339ed613a6820378ab4f935fde1f2a1253ff4a',
};
