// THIS FILE IS AUTOGENERATED BY `tool/regenerate_hashes.dart`. TO UPDATE, RUN:
//
//   dart tool/regenerate_hashes.dart <github release tag>
//

import 'dart:convert';
import 'dart:io';

import 'package:code_assets/code_assets.dart';
import 'package:crypto/crypto.dart';

/// GitHub repository hosting prebuilt release artifacts and SLSA provenance attestations.
const repository = 'sigurdm/scientific_dart';

/// Release tag for prebuilt `ndarray` binaries.
const version = 'artifacts-v0.0.2';

/// Combined SHA-256 digest of `hook/` native source files at [version].
const nativeSourceHash =
    '1e736ab5003778b2866454d0ae2ce2d1edb3af834a82639e3d791702f096aac1';

/// Lists the tracked native source files in `hook/` under [packageRoot].
List<File> nativeSourceFiles(Uri packageRoot) {
  final hookDir = Directory.fromUri(packageRoot.resolve('hook/'));
  if (!hookDir.existsSync()) return const [];
  final files = hookDir.listSync().whereType<File>().where((file) {
    final name = file.uri.pathSegments.last;
    return name.endsWith('.dart') ||
        name.endsWith('.c') ||
        name.endsWith('.cpp') ||
        name.endsWith('.h') ||
        name.endsWith('.def');
  }).toList();
  files.sort(
    (a, b) => a.uri.pathSegments.last.compareTo(b.uri.pathSegments.last),
  );
  return files;
}

/// Computes the combined SHA-256 digest of `hook/` native source files under [packageRoot].
String computeNativeSourceHash(Uri packageRoot) {
  final buffer = StringBuffer();
  for (final file in nativeSourceFiles(packageRoot)) {
    final name = file.uri.pathSegments.last;
    final normalized = file.readAsStringSync().replaceAll('\r\n', '\n');
    final fileDigest = sha256.convert(utf8.encode(normalized)).toString();
    buffer.writeln('$name:$fileDigest');
  }
  return sha256.convert(utf8.encode(buffer.toString())).toString();
}

/// Canonical release artifact filename for `(os, arch)`.
String ndarrayArtifactName(OS os, Architecture arch) {
  final ext = switch (os) {
    OS.windows => 'dll',
    OS.macOS || OS.iOS => 'dylib',
    _ => 'so',
  };
  return 'ndarray-${os.name}-${arch.name}.$ext';
}

/// SHA-256 digests for prebuilt `ndarray` binaries indexed by `(OS, Architecture)`.
const fileHashes = <(OS, Architecture), String>{
  (OS.linux, Architecture.x64):
      'ed3b0f78477f5165d81b5cdb7dd6a63393c39c6625cdd42470917f51ff17f9bc',
  (OS.linux, Architecture.arm64):
      '000ee9ac1d2ee39cd0b94954703204d14c6331c1c713429d4b42fd9dabc954d3',
  (OS.macOS, Architecture.arm64):
      '1856c03411e083f2e489d98ac8df995b14b1213bd411d3f63333e048366d2c3b',
  (OS.macOS, Architecture.x64):
      '89d1c215bda8843be8339d5eb98d6601be0f15337e773c62608821d8c88e917e',
  (OS.windows, Architecture.x64):
      'a59697e50d5c6b54f1cc357c11339ed613a6820378ab4f935fde1f2a1253ff4a',
};
