// THIS FILE IS AUTOGENERATED BY `tool/regenerate_hashes.dart`. TO UPDATE, RUN:
//
//   dart tool/regenerate_hashes.dart <github release tag>
//

import 'package:code_assets/code_assets.dart';

/// GitHub repository hosting prebuilt release artifacts and SLSA provenance attestations.
const repository = 'sigurdm/scientific_dart';

/// Release tag for prebuilt `pocketfft` binaries.
const version = 'artifacts-v0.0.2';

/// Canonical release artifact filename for `(os, arch)`.
String pocketfftArtifactName(OS os, Architecture arch) {
  final ext = switch (os) {
    OS.windows => 'dll',
    OS.macOS || OS.iOS => 'dylib',
    _ => 'so',
  };
  return 'pocketfft-${os.name}-${arch.name}.$ext';
}

/// SHA-256 digests for prebuilt `pocketfft` binaries indexed by `(OS, Architecture)`.
const fileHashes = <(OS, Architecture), String>{
  (OS.linux, Architecture.x64):
      'f3581010c46b4b76090ad0fd56e85007001b105a6bdde361f2be2baa2287e257',
  (OS.linux, Architecture.arm64):
      '0000000000000000000000000000000000000000000000000000000000000000',
  (OS.macOS, Architecture.arm64):
      '0000000000000000000000000000000000000000000000000000000000000000',
  (OS.macOS, Architecture.x64):
      '0000000000000000000000000000000000000000000000000000000000000000',
  (OS.windows, Architecture.x64):
      '0000000000000000000000000000000000000000000000000000000000000000',
};
