name: math_workspace
environment:
  sdk: ^3.11.5
workspace:
  - pkgs/openblas
  - pkgs/ndarray
  - pkgs/pocketfft
  - pkgs/guitar_tuner
  - pkgs/ndarray_ma
dependencies:
  http: ^1.6.0

dev_dependencies:
  ffigen: ^20.1.1

