import 'package:ndarray/ndarray.dart';
import 'package:symbolic_dart/symbolic_dart.dart';

void main() {
  print('=== 1. Non-Linear Root Solving with Analytical Jacobians ===');
  // Intersection of circle x^2 + y^2 = 25 and line y - x = 1
  // Exact intersection in first quadrant: x = 3, y = 4
  final x = Symbol('x');
  final y = Symbol('y');

  final eq1 = (x ^ 2) + (y ^ 2) - Integer(25);
  final eq2 = y - x - Integer(1);

  print('System of equations:');
  print('  f_1(x, y) = $eq1 = 0');
  print('  f_2(x, y) = $eq2 = 0');

  // Let's inspect the analytical Jacobian matrix generated by SymbolicMatrix
  final vecF = SymbolicMatrix.fromVector([eq1, eq2]);
  final jacJ = vecF.jacobian([x, y]);
  print('\nAnalytical Jacobian matrix J(x, y):');
  print('  [ ${jacJ.getCell(0, 0)} , ${jacJ.getCell(0, 1)} ]');
  print('  [ ${jacJ.getCell(1, 0)} , ${jacJ.getCell(1, 1)} ]\n');

  final initialGuess = NDArray.fromList([2.0, 3.0], [2], DType.float64);
  print('Starting Newton-Raphson from initial guess: $initialGuess');

  final newton = SymbolicOptimizer.solveNewtonRaphson(
    equations: [eq1, eq2],
    variables: [x, y],
    x0: initialGuess,
  );

  print(
    'Converged in ${newton.iterations} iterations to root:\n'
    '  x* = ${newton.solution.getCell([0])}\n'
    '  y* = ${newton.solution.getCell([1])}\n'
    '  Max Residual ||f||_inf = ${newton.residual}\n',
  );

  print('=== 2. Gradient Descent Optimization on Rosenbrock-like Loss ===');
  // L(x, y) = 10*(y - x^2)^2 + (1 - x)^2
  final loss = (Integer(10) * (((y - (x ^ 2)) ^ 2))) + (((Expr.one - x) ^ 2));
  print('Loss function L(x, y) = $loss');

  final gradX = loss.diff(x);
  final gradY = loss.diff(y);
  print('Analytical Gradient \\nabla L = [ $gradX,  $gradY ]^T\n');

  final gdStart = NDArray.fromList([0.0, 0.0], [2], DType.float64);
  final gdResult = SymbolicOptimizer.minimizeGradientDescent(
    objective: loss,
    variables: [x, y],
    x0: gdStart,
    learningRate: 0.01,
    maxIterations: 500,
  );

  print(
    'Gradient Descent converged:\n'
    '  x* = ${gdResult.solution.getCell([0])}\n'
    '  y* = ${gdResult.solution.getCell([1])}\n'
    '  Final Loss = ${gdResult.loss}\n'
    '  ||\\nabla L||_inf = ${gdResult.gradientNorm}',
  );
}
