// Automatically generated by ffigen. DO NOT EDIT.
// ignore_for_file: type=lint, unused_element, unused_field, camel_case_types, non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: unused_import
@ffi.DefaultAsset('package:pocketfft/pocketfft')
library;

import 'dart:ffi' as ffi;

@ffi.Native<ffi.Size Function()>()
external int __ctype_get_mb_cur_max();

@ffi.Native<ffi.Double Function(ffi.Pointer<ffi.Char>)>()
external double atof(ffi.Pointer<ffi.Char> __nptr);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>)>()
external int atoi(ffi.Pointer<ffi.Char> __nptr);

@ffi.Native<ffi.Long Function(ffi.Pointer<ffi.Char>)>()
external int atol(ffi.Pointer<ffi.Char> __nptr);

@ffi.Native<ffi.LongLong Function(ffi.Pointer<ffi.Char>)>()
external int atoll(ffi.Pointer<ffi.Char> __nptr);

@ffi.Native<
  ffi.Double Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)
>()
external double strtod(
  ffi.Pointer<ffi.Char> __nptr,
  ffi.Pointer<ffi.Pointer<ffi.Char>> __endptr,
);

@ffi.Native<
  ffi.Float Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)
>()
external double strtof(
  ffi.Pointer<ffi.Char> __nptr,
  ffi.Pointer<ffi.Pointer<ffi.Char>> __endptr,
);

@ffi.Native<
  ffi.Long Function(
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
    ffi.Int,
  )
>()
external int strtol(
  ffi.Pointer<ffi.Char> __nptr,
  ffi.Pointer<ffi.Pointer<ffi.Char>> __endptr,
  int __base,
);

@ffi.Native<
  ffi.UnsignedLong Function(
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
    ffi.Int,
  )
>()
external int strtoul(
  ffi.Pointer<ffi.Char> __nptr,
  ffi.Pointer<ffi.Pointer<ffi.Char>> __endptr,
  int __base,
);

@ffi.Native<
  ffi.LongLong Function(
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
    ffi.Int,
  )
>()
external int strtoq(
  ffi.Pointer<ffi.Char> __nptr,
  ffi.Pointer<ffi.Pointer<ffi.Char>> __endptr,
  int __base,
);

@ffi.Native<
  ffi.UnsignedLongLong Function(
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
    ffi.Int,
  )
>()
external int strtouq(
  ffi.Pointer<ffi.Char> __nptr,
  ffi.Pointer<ffi.Pointer<ffi.Char>> __endptr,
  int __base,
);

@ffi.Native<
  ffi.LongLong Function(
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
    ffi.Int,
  )
>()
external int strtoll(
  ffi.Pointer<ffi.Char> __nptr,
  ffi.Pointer<ffi.Pointer<ffi.Char>> __endptr,
  int __base,
);

@ffi.Native<
  ffi.UnsignedLongLong Function(
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
    ffi.Int,
  )
>()
external int strtoull(
  ffi.Pointer<ffi.Char> __nptr,
  ffi.Pointer<ffi.Pointer<ffi.Char>> __endptr,
  int __base,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Long)>()
external ffi.Pointer<ffi.Char> l64a(int __n);

@ffi.Native<ffi.Long Function(ffi.Pointer<ffi.Char>)>()
external int a64l(ffi.Pointer<ffi.Char> __s);

@ffi.Native<
  ffi.Int Function(
    ffi.Int,
    ffi.Pointer<fd_set>,
    ffi.Pointer<fd_set>,
    ffi.Pointer<fd_set>,
    ffi.Pointer<timeval>,
  )
>()
external int select(
  int __nfds,
  ffi.Pointer<fd_set> __readfds,
  ffi.Pointer<fd_set> __writefds,
  ffi.Pointer<fd_set> __exceptfds,
  ffi.Pointer<timeval> __timeout,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Int,
    ffi.Pointer<fd_set>,
    ffi.Pointer<fd_set>,
    ffi.Pointer<fd_set>,
    ffi.Pointer<timespec>,
    ffi.Pointer<__sigset_t>,
  )
>()
external int pselect(
  int __nfds,
  ffi.Pointer<fd_set> __readfds,
  ffi.Pointer<fd_set> __writefds,
  ffi.Pointer<fd_set> __exceptfds,
  ffi.Pointer<timespec> __timeout,
  ffi.Pointer<__sigset_t> __sigmask,
);

@ffi.Native<ffi.Long Function()>()
external int random();

@ffi.Native<ffi.Void Function(ffi.UnsignedInt)>()
external void srandom(int __seed);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(
    ffi.UnsignedInt,
    ffi.Pointer<ffi.Char>,
    ffi.Size,
  )
>()
external ffi.Pointer<ffi.Char> initstate(
  int __seed,
  ffi.Pointer<ffi.Char> __statebuf,
  int __statelen,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>()
external ffi.Pointer<ffi.Char> setstate(ffi.Pointer<ffi.Char> __statebuf);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<random_data>, ffi.Pointer<ffi.Int32>)
>()
external int random_r(
  ffi.Pointer<random_data> __buf,
  ffi.Pointer<ffi.Int32> __result,
);

@ffi.Native<ffi.Int Function(ffi.UnsignedInt, ffi.Pointer<random_data>)>()
external int srandom_r(int __seed, ffi.Pointer<random_data> __buf);

@ffi.Native<
  ffi.Int Function(
    ffi.UnsignedInt,
    ffi.Pointer<ffi.Char>,
    ffi.Size,
    ffi.Pointer<random_data>,
  )
>()
external int initstate_r(
  int __seed,
  ffi.Pointer<ffi.Char> __statebuf,
  int __statelen,
  ffi.Pointer<random_data> __buf,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<random_data>)>()
external int setstate_r(
  ffi.Pointer<ffi.Char> __statebuf,
  ffi.Pointer<random_data> __buf,
);

@ffi.Native<ffi.Int Function()>()
external int rand();

@ffi.Native<ffi.Void Function(ffi.UnsignedInt)>()
external void srand(int __seed);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.UnsignedInt>)>()
external int rand_r(ffi.Pointer<ffi.UnsignedInt> __seed);

@ffi.Native<ffi.Double Function()>()
external double drand48();

@ffi.Native<ffi.Double Function(ffi.Pointer<ffi.UnsignedShort>)>()
external double erand48(ffi.Pointer<ffi.UnsignedShort> __xsubi);

@ffi.Native<ffi.Long Function()>()
external int lrand48();

@ffi.Native<ffi.Long Function(ffi.Pointer<ffi.UnsignedShort>)>()
external int nrand48(ffi.Pointer<ffi.UnsignedShort> __xsubi);

@ffi.Native<ffi.Long Function()>()
external int mrand48();

@ffi.Native<ffi.Long Function(ffi.Pointer<ffi.UnsignedShort>)>()
external int jrand48(ffi.Pointer<ffi.UnsignedShort> __xsubi);

@ffi.Native<ffi.Void Function(ffi.Long)>()
external void srand48(int __seedval);

@ffi.Native<
  ffi.Pointer<ffi.UnsignedShort> Function(ffi.Pointer<ffi.UnsignedShort>)
>()
external ffi.Pointer<ffi.UnsignedShort> seed48(
  ffi.Pointer<ffi.UnsignedShort> __seed16v,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.UnsignedShort>)>()
external void lcong48(ffi.Pointer<ffi.UnsignedShort> __param);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<drand48_data>, ffi.Pointer<ffi.Double>)
>()
external int drand48_r(
  ffi.Pointer<drand48_data> __buffer,
  ffi.Pointer<ffi.Double> __result,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<ffi.UnsignedShort>,
    ffi.Pointer<drand48_data>,
    ffi.Pointer<ffi.Double>,
  )
>()
external int erand48_r(
  ffi.Pointer<ffi.UnsignedShort> __xsubi,
  ffi.Pointer<drand48_data> __buffer,
  ffi.Pointer<ffi.Double> __result,
);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<drand48_data>, ffi.Pointer<ffi.Long>)
>()
external int lrand48_r(
  ffi.Pointer<drand48_data> __buffer,
  ffi.Pointer<ffi.Long> __result,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<ffi.UnsignedShort>,
    ffi.Pointer<drand48_data>,
    ffi.Pointer<ffi.Long>,
  )
>()
external int nrand48_r(
  ffi.Pointer<ffi.UnsignedShort> __xsubi,
  ffi.Pointer<drand48_data> __buffer,
  ffi.Pointer<ffi.Long> __result,
);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<drand48_data>, ffi.Pointer<ffi.Long>)
>()
external int mrand48_r(
  ffi.Pointer<drand48_data> __buffer,
  ffi.Pointer<ffi.Long> __result,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<ffi.UnsignedShort>,
    ffi.Pointer<drand48_data>,
    ffi.Pointer<ffi.Long>,
  )
>()
external int jrand48_r(
  ffi.Pointer<ffi.UnsignedShort> __xsubi,
  ffi.Pointer<drand48_data> __buffer,
  ffi.Pointer<ffi.Long> __result,
);

@ffi.Native<ffi.Int Function(ffi.Long, ffi.Pointer<drand48_data>)>()
external int srand48_r(int __seedval, ffi.Pointer<drand48_data> __buffer);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<ffi.UnsignedShort>, ffi.Pointer<drand48_data>)
>()
external int seed48_r(
  ffi.Pointer<ffi.UnsignedShort> __seed16v,
  ffi.Pointer<drand48_data> __buffer,
);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<ffi.UnsignedShort>, ffi.Pointer<drand48_data>)
>()
external int lcong48_r(
  ffi.Pointer<ffi.UnsignedShort> __param,
  ffi.Pointer<drand48_data> __buffer,
);

@ffi.Native<__uint32_t Function()>()
external int arc4random();

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Size)>()
external void arc4random_buf(ffi.Pointer<ffi.Void> __buf, int __size);

@ffi.Native<__uint32_t Function(__uint32_t)>()
external int arc4random_uniform(int __upper_bound);

@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Size)>()
external ffi.Pointer<ffi.Void> malloc(int __size);

@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Size, ffi.Size)>()
external ffi.Pointer<ffi.Void> calloc(int __nmemb, int __size);

@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>, ffi.Size)>()
external ffi.Pointer<ffi.Void> realloc(ffi.Pointer<ffi.Void> __ptr, int __size);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void free(ffi.Pointer<ffi.Void> __ptr);

@ffi.Native<
  ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>, ffi.Size, ffi.Size)
>()
external ffi.Pointer<ffi.Void> reallocarray(
  ffi.Pointer<ffi.Void> __ptr,
  int __nmemb,
  int __size,
);

@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Size)>()
external ffi.Pointer<ffi.Void> alloca(int __size);

@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Size)>()
external ffi.Pointer<ffi.Void> valloc(int __size);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<ffi.Pointer<ffi.Void>>, ffi.Size, ffi.Size)
>()
external int posix_memalign(
  ffi.Pointer<ffi.Pointer<ffi.Void>> __memptr,
  int __alignment,
  int __size,
);

@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Size, ffi.Size)>()
external ffi.Pointer<ffi.Void> aligned_alloc(int __alignment, int __size);

@ffi.Native<ffi.Void Function()>()
external void abort();

@ffi.Native<
  ffi.Int Function(ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>>)
>()
external int atexit(
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>> __func,
);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>>)
>()
external int at_quick_exit(
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>> __func,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(ffi.Int __status, ffi.Pointer<ffi.Void> __arg)
      >
    >,
    ffi.Pointer<ffi.Void>,
  )
>()
external int on_exit(
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(ffi.Int __status, ffi.Pointer<ffi.Void> __arg)
    >
  >
  __func,
  ffi.Pointer<ffi.Void> __arg,
);

@ffi.Native<ffi.Void Function(ffi.Int)>()
external void exit(int __status);

@ffi.Native<ffi.Void Function(ffi.Int)>()
external void quick_exit(int __status);

@ffi.Native<ffi.Void Function(ffi.Int)>()
external void _Exit(int __status);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>()
external ffi.Pointer<ffi.Char> getenv(ffi.Pointer<ffi.Char> __name);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>)>()
external int putenv(ffi.Pointer<ffi.Char> __string);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Int)
>()
external int setenv(
  ffi.Pointer<ffi.Char> __name,
  ffi.Pointer<ffi.Char> __value,
  int __replace,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>)>()
external int unsetenv(ffi.Pointer<ffi.Char> __name);

@ffi.Native<ffi.Int Function()>()
external int clearenv();

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>()
external ffi.Pointer<ffi.Char> mktemp(ffi.Pointer<ffi.Char> __template);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>)>()
external int mkstemp(ffi.Pointer<ffi.Char> __template);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Int)>()
external int mkstemps(ffi.Pointer<ffi.Char> __template, int __suffixlen);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>()
external ffi.Pointer<ffi.Char> mkdtemp(ffi.Pointer<ffi.Char> __template);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>)>()
external int system(ffi.Pointer<ffi.Char> __command);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
>()
external ffi.Pointer<ffi.Char> realpath(
  ffi.Pointer<ffi.Char> __name,
  ffi.Pointer<ffi.Char> __resolved,
);

@ffi.Native<
  ffi.Pointer<ffi.Void> Function(
    ffi.Pointer<ffi.Void>,
    ffi.Pointer<ffi.Void>,
    ffi.Size,
    ffi.Size,
    __compar_fn_t,
  )
>()
external ffi.Pointer<ffi.Void> bsearch(
  ffi.Pointer<ffi.Void> __key,
  ffi.Pointer<ffi.Void> __base,
  int __nmemb,
  int __size,
  __compar_fn_t __compar,
);

@ffi.Native<
  ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Size, ffi.Size, __compar_fn_t)
>()
external void qsort(
  ffi.Pointer<ffi.Void> __base,
  int __nmemb,
  int __size,
  __compar_fn_t __compar,
);

@ffi.Native<ffi.Int Function(ffi.Int)>()
external int abs(int __x);

@ffi.Native<ffi.Long Function(ffi.Long)>()
external int labs(int __x);

@ffi.Native<ffi.LongLong Function(ffi.LongLong)>()
external int llabs(int __x);

@ffi.Native<div_t Function(ffi.Int, ffi.Int)>()
external div_t div(int __numer, int __denom);

@ffi.Native<ldiv_t Function(ffi.Long, ffi.Long)>()
external ldiv_t ldiv(int __numer, int __denom);

@ffi.Native<lldiv_t Function(ffi.LongLong, ffi.LongLong)>()
external lldiv_t lldiv(int __numer, int __denom);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(
    ffi.Double,
    ffi.Int,
    ffi.Pointer<ffi.Int>,
    ffi.Pointer<ffi.Int>,
  )
>()
external ffi.Pointer<ffi.Char> ecvt(
  double __value,
  int __ndigit,
  ffi.Pointer<ffi.Int> __decpt,
  ffi.Pointer<ffi.Int> __sign,
);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(
    ffi.Double,
    ffi.Int,
    ffi.Pointer<ffi.Int>,
    ffi.Pointer<ffi.Int>,
  )
>()
external ffi.Pointer<ffi.Char> fcvt(
  double __value,
  int __ndigit,
  ffi.Pointer<ffi.Int> __decpt,
  ffi.Pointer<ffi.Int> __sign,
);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(ffi.Double, ffi.Int, ffi.Pointer<ffi.Char>)
>()
external ffi.Pointer<ffi.Char> gcvt(
  double __value,
  int __ndigit,
  ffi.Pointer<ffi.Char> __buf,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Double,
    ffi.Int,
    ffi.Pointer<ffi.Int>,
    ffi.Pointer<ffi.Int>,
    ffi.Pointer<ffi.Char>,
    ffi.Size,
  )
>()
external int ecvt_r(
  double __value,
  int __ndigit,
  ffi.Pointer<ffi.Int> __decpt,
  ffi.Pointer<ffi.Int> __sign,
  ffi.Pointer<ffi.Char> __buf,
  int __len,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Double,
    ffi.Int,
    ffi.Pointer<ffi.Int>,
    ffi.Pointer<ffi.Int>,
    ffi.Pointer<ffi.Char>,
    ffi.Size,
  )
>()
external int fcvt_r(
  double __value,
  int __ndigit,
  ffi.Pointer<ffi.Int> __decpt,
  ffi.Pointer<ffi.Int> __sign,
  ffi.Pointer<ffi.Char> __buf,
  int __len,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Size)>()
external int mblen(ffi.Pointer<ffi.Char> __s, int __n);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<ffi.WChar>, ffi.Pointer<ffi.Char>, ffi.Size)
>()
external int mbtowc(
  ffi.Pointer<ffi.WChar> __pwc,
  ffi.Pointer<ffi.Char> __s,
  int __n,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.WChar)>()
external int wctomb(ffi.Pointer<ffi.Char> __s, int __wchar);

@ffi.Native<
  ffi.Size Function(ffi.Pointer<ffi.WChar>, ffi.Pointer<ffi.Char>, ffi.Size)
>()
external int mbstowcs(
  ffi.Pointer<ffi.WChar> __pwcs,
  ffi.Pointer<ffi.Char> __s,
  int __n,
);

@ffi.Native<
  ffi.Size Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.WChar>, ffi.Size)
>()
external int wcstombs(
  ffi.Pointer<ffi.Char> __s,
  ffi.Pointer<ffi.WChar> __pwcs,
  int __n,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>)>()
external int rpmatch(ffi.Pointer<ffi.Char> __response);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
  )
>()
external int getsubopt(
  ffi.Pointer<ffi.Pointer<ffi.Char>> __optionp,
  ffi.Pointer<ffi.Pointer<ffi.Char>> __tokens,
  ffi.Pointer<ffi.Pointer<ffi.Char>> __valuep,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Double>, ffi.Int)>()
external int getloadavg(ffi.Pointer<ffi.Double> __loadavg, int __nelem);

@ffi.Native<ffi.Pointer<FILE>>()
external ffi.Pointer<FILE> stdin;

@ffi.Native<ffi.Pointer<FILE>>()
external ffi.Pointer<FILE> stdout;

@ffi.Native<ffi.Pointer<FILE>>()
external ffi.Pointer<FILE> stderr;

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>)>()
external int remove(ffi.Pointer<ffi.Char> __filename);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>()
external int rename(ffi.Pointer<ffi.Char> __old, ffi.Pointer<ffi.Char> __new);

@ffi.Native<
  ffi.Int Function(
    ffi.Int,
    ffi.Pointer<ffi.Char>,
    ffi.Int,
    ffi.Pointer<ffi.Char>,
  )
>()
external int renameat(
  int __oldfd,
  ffi.Pointer<ffi.Char> __old,
  int __newfd,
  ffi.Pointer<ffi.Char> __new,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<FILE>)>()
external int fclose(ffi.Pointer<FILE> __stream);

@ffi.Native<ffi.Pointer<FILE> Function()>()
external ffi.Pointer<FILE> tmpfile();

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>()
external ffi.Pointer<ffi.Char> tmpnam(ffi.Pointer<ffi.Char> arg0);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>()
external ffi.Pointer<ffi.Char> tmpnam_r(ffi.Pointer<ffi.Char> __s);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
>()
external ffi.Pointer<ffi.Char> tempnam(
  ffi.Pointer<ffi.Char> __dir,
  ffi.Pointer<ffi.Char> __pfx,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<FILE>)>()
external int fflush(ffi.Pointer<FILE> __stream);

@ffi.Native<ffi.Int Function(ffi.Pointer<FILE>)>()
external int fflush_unlocked(ffi.Pointer<FILE> __stream);

@ffi.Native<
  ffi.Pointer<FILE> Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
>()
external ffi.Pointer<FILE> fopen(
  ffi.Pointer<ffi.Char> __filename,
  ffi.Pointer<ffi.Char> __modes,
);

@ffi.Native<
  ffi.Pointer<FILE> Function(
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<FILE>,
  )
>()
external ffi.Pointer<FILE> freopen(
  ffi.Pointer<ffi.Char> __filename,
  ffi.Pointer<ffi.Char> __modes,
  ffi.Pointer<FILE> __stream,
);

@ffi.Native<ffi.Pointer<FILE> Function(ffi.Int, ffi.Pointer<ffi.Char>)>()
external ffi.Pointer<FILE> fdopen(int __fd, ffi.Pointer<ffi.Char> __modes);

@ffi.Native<
  ffi.Pointer<FILE> Function(
    ffi.Pointer<ffi.Void>,
    ffi.Pointer<ffi.Char>,
    cookie_io_functions_t,
  )
>()
external ffi.Pointer<FILE> fopencookie(
  ffi.Pointer<ffi.Void> __magic_cookie,
  ffi.Pointer<ffi.Char> __modes,
  cookie_io_functions_t __io_funcs,
);

@ffi.Native<
  ffi.Pointer<FILE> Function(
    ffi.Pointer<ffi.Void>,
    ffi.Size,
    ffi.Pointer<ffi.Char>,
  )
>()
external ffi.Pointer<FILE> fmemopen(
  ffi.Pointer<ffi.Void> __s,
  int __len,
  ffi.Pointer<ffi.Char> __modes,
);

@ffi.Native<
  ffi.Pointer<FILE> Function(
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
    ffi.Pointer<ffi.Size>,
  )
>()
external ffi.Pointer<FILE> open_memstream(
  ffi.Pointer<ffi.Pointer<ffi.Char>> __bufloc,
  ffi.Pointer<ffi.Size> __sizeloc,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<FILE>, ffi.Pointer<ffi.Char>)>()
external void setbuf(ffi.Pointer<FILE> __stream, ffi.Pointer<ffi.Char> __buf);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<FILE>, ffi.Pointer<ffi.Char>, ffi.Int, ffi.Size)
>()
external int setvbuf(
  ffi.Pointer<FILE> __stream,
  ffi.Pointer<ffi.Char> __buf,
  int __modes,
  int __n,
);

@ffi.Native<
  ffi.Void Function(ffi.Pointer<FILE>, ffi.Pointer<ffi.Char>, ffi.Size)
>()
external void setbuffer(
  ffi.Pointer<FILE> __stream,
  ffi.Pointer<ffi.Char> __buf,
  int __size,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<FILE>)>()
external void setlinebuf(ffi.Pointer<FILE> __stream);

@ffi.Native<ffi.Int Function(ffi.Pointer<FILE>, ffi.Pointer<ffi.Char>)>()
external int fprintf(
  ffi.Pointer<FILE> __stream,
  ffi.Pointer<ffi.Char> __format,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>)>()
external int printf(ffi.Pointer<ffi.Char> __format);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>()
external int sprintf(ffi.Pointer<ffi.Char> __s, ffi.Pointer<ffi.Char> __format);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<FILE>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<__va_list_tag>,
  )
>()
external int vfprintf(
  ffi.Pointer<FILE> __s,
  ffi.Pointer<ffi.Char> __format,
  ffi.Pointer<__va_list_tag> __arg,
);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<__va_list_tag>)
>()
external int vprintf(
  ffi.Pointer<ffi.Char> __format,
  ffi.Pointer<__va_list_tag> __arg,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<__va_list_tag>,
  )
>()
external int vsprintf(
  ffi.Pointer<ffi.Char> __s,
  ffi.Pointer<ffi.Char> __format,
  ffi.Pointer<__va_list_tag> __arg,
);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Size, ffi.Pointer<ffi.Char>)
>()
external int snprintf(
  ffi.Pointer<ffi.Char> __s,
  int __maxlen,
  ffi.Pointer<ffi.Char> __format,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<ffi.Char>,
    ffi.Size,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<__va_list_tag>,
  )
>()
external int vsnprintf(
  ffi.Pointer<ffi.Char> __s,
  int __maxlen,
  ffi.Pointer<ffi.Char> __format,
  ffi.Pointer<__va_list_tag> __arg,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<__va_list_tag>,
  )
>()
external int vasprintf(
  ffi.Pointer<ffi.Pointer<ffi.Char>> __ptr,
  ffi.Pointer<ffi.Char> __f,
  ffi.Pointer<__va_list_tag> __arg,
);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<ffi.Pointer<ffi.Char>>, ffi.Pointer<ffi.Char>)
>()
external int __asprintf(
  ffi.Pointer<ffi.Pointer<ffi.Char>> __ptr,
  ffi.Pointer<ffi.Char> __fmt,
);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<ffi.Pointer<ffi.Char>>, ffi.Pointer<ffi.Char>)
>()
external int asprintf(
  ffi.Pointer<ffi.Pointer<ffi.Char>> __ptr,
  ffi.Pointer<ffi.Char> __fmt,
);

@ffi.Native<
  ffi.Int Function(ffi.Int, ffi.Pointer<ffi.Char>, ffi.Pointer<__va_list_tag>)
>()
external int vdprintf(
  int __fd,
  ffi.Pointer<ffi.Char> __fmt,
  ffi.Pointer<__va_list_tag> __arg,
);

@ffi.Native<ffi.Int Function(ffi.Int, ffi.Pointer<ffi.Char>)>()
external int dprintf(int __fd, ffi.Pointer<ffi.Char> __fmt);

@ffi.Native<ffi.Int Function(ffi.Pointer<FILE>, ffi.Pointer<ffi.Char>)>()
external int fscanf(ffi.Pointer<FILE> __stream, ffi.Pointer<ffi.Char> __format);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>)>()
external int scanf(ffi.Pointer<ffi.Char> __format);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>()
external int sscanf(ffi.Pointer<ffi.Char> __s, ffi.Pointer<ffi.Char> __format);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<FILE>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<__va_list_tag>,
  )
>()
external int vfscanf(
  ffi.Pointer<FILE> __s,
  ffi.Pointer<ffi.Char> __format,
  ffi.Pointer<__va_list_tag> __arg,
);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<__va_list_tag>)
>()
external int vscanf(
  ffi.Pointer<ffi.Char> __format,
  ffi.Pointer<__va_list_tag> __arg,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<__va_list_tag>,
  )
>()
external int vsscanf(
  ffi.Pointer<ffi.Char> __s,
  ffi.Pointer<ffi.Char> __format,
  ffi.Pointer<__va_list_tag> __arg,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<FILE>)>()
external int fgetc(ffi.Pointer<FILE> __stream);

@ffi.Native<ffi.Int Function(ffi.Pointer<FILE>)>()
external int getc(ffi.Pointer<FILE> __stream);

@ffi.Native<ffi.Int Function()>()
external int getchar();

@ffi.Native<ffi.Int Function(ffi.Pointer<FILE>)>()
external int getc_unlocked(ffi.Pointer<FILE> __stream);

@ffi.Native<ffi.Int Function()>()
external int getchar_unlocked();

@ffi.Native<ffi.Int Function(ffi.Pointer<FILE>)>()
external int fgetc_unlocked(ffi.Pointer<FILE> __stream);

@ffi.Native<ffi.Int Function(ffi.Int, ffi.Pointer<FILE>)>()
external int fputc(int __c, ffi.Pointer<FILE> __stream);

@ffi.Native<ffi.Int Function(ffi.Int, ffi.Pointer<FILE>)>()
external int putc(int __c, ffi.Pointer<FILE> __stream);

@ffi.Native<ffi.Int Function(ffi.Int)>()
external int putchar(int __c);

@ffi.Native<ffi.Int Function(ffi.Int, ffi.Pointer<FILE>)>()
external int fputc_unlocked(int __c, ffi.Pointer<FILE> __stream);

@ffi.Native<ffi.Int Function(ffi.Int, ffi.Pointer<FILE>)>()
external int putc_unlocked(int __c, ffi.Pointer<FILE> __stream);

@ffi.Native<ffi.Int Function(ffi.Int)>()
external int putchar_unlocked(int __c);

@ffi.Native<ffi.Int Function(ffi.Pointer<FILE>)>()
external int getw(ffi.Pointer<FILE> __stream);

@ffi.Native<ffi.Int Function(ffi.Int, ffi.Pointer<FILE>)>()
external int putw(int __w, ffi.Pointer<FILE> __stream);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(
    ffi.Pointer<ffi.Char>,
    ffi.Int,
    ffi.Pointer<FILE>,
  )
>()
external ffi.Pointer<ffi.Char> fgets(
  ffi.Pointer<ffi.Char> __s,
  int __n,
  ffi.Pointer<FILE> __stream,
);

@ffi.Native<
  __ssize_t Function(
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
    ffi.Pointer<ffi.Size>,
    ffi.Int,
    ffi.Pointer<FILE>,
  )
>()
external int __getdelim(
  ffi.Pointer<ffi.Pointer<ffi.Char>> __lineptr,
  ffi.Pointer<ffi.Size> __n,
  int __delimiter,
  ffi.Pointer<FILE> __stream,
);

@ffi.Native<
  __ssize_t Function(
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
    ffi.Pointer<ffi.Size>,
    ffi.Int,
    ffi.Pointer<FILE>,
  )
>()
external int getdelim(
  ffi.Pointer<ffi.Pointer<ffi.Char>> __lineptr,
  ffi.Pointer<ffi.Size> __n,
  int __delimiter,
  ffi.Pointer<FILE> __stream,
);

@ffi.Native<
  __ssize_t Function(
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
    ffi.Pointer<ffi.Size>,
    ffi.Pointer<FILE>,
  )
>()
external int getline(
  ffi.Pointer<ffi.Pointer<ffi.Char>> __lineptr,
  ffi.Pointer<ffi.Size> __n,
  ffi.Pointer<FILE> __stream,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<FILE>)>()
external int fputs(ffi.Pointer<ffi.Char> __s, ffi.Pointer<FILE> __stream);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>)>()
external int puts(ffi.Pointer<ffi.Char> __s);

@ffi.Native<ffi.Int Function(ffi.Int, ffi.Pointer<FILE>)>()
external int ungetc(int __c, ffi.Pointer<FILE> __stream);

@ffi.Native<
  ffi.UnsignedLong Function(
    ffi.Pointer<ffi.Void>,
    ffi.Size,
    ffi.Size,
    ffi.Pointer<FILE>,
  )
>()
external int fread(
  ffi.Pointer<ffi.Void> __ptr,
  int __size,
  int __n,
  ffi.Pointer<FILE> __stream,
);

@ffi.Native<
  ffi.UnsignedLong Function(
    ffi.Pointer<ffi.Void>,
    ffi.Size,
    ffi.Size,
    ffi.Pointer<FILE>,
  )
>()
external int fwrite(
  ffi.Pointer<ffi.Void> __ptr,
  int __size,
  int __n,
  ffi.Pointer<FILE> __s,
);

@ffi.Native<
  ffi.Size Function(
    ffi.Pointer<ffi.Void>,
    ffi.Size,
    ffi.Size,
    ffi.Pointer<FILE>,
  )
>()
external int fread_unlocked(
  ffi.Pointer<ffi.Void> __ptr,
  int __size,
  int __n,
  ffi.Pointer<FILE> __stream,
);

@ffi.Native<
  ffi.Size Function(
    ffi.Pointer<ffi.Void>,
    ffi.Size,
    ffi.Size,
    ffi.Pointer<FILE>,
  )
>()
external int fwrite_unlocked(
  ffi.Pointer<ffi.Void> __ptr,
  int __size,
  int __n,
  ffi.Pointer<FILE> __stream,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<FILE>, ffi.Long, ffi.Int)>()
external int fseek(ffi.Pointer<FILE> __stream, int __off, int __whence);

@ffi.Native<ffi.Long Function(ffi.Pointer<FILE>)>()
external int ftell(ffi.Pointer<FILE> __stream);

@ffi.Native<ffi.Void Function(ffi.Pointer<FILE>)>()
external void rewind(ffi.Pointer<FILE> __stream);

@ffi.Native<ffi.Int Function(ffi.Pointer<FILE>, __off_t, ffi.Int)>()
external int fseeko(ffi.Pointer<FILE> __stream, int __off, int __whence);

@ffi.Native<__off_t Function(ffi.Pointer<FILE>)>()
external int ftello(ffi.Pointer<FILE> __stream);

@ffi.Native<ffi.Int Function(ffi.Pointer<FILE>, ffi.Pointer<fpos_t>)>()
external int fgetpos(ffi.Pointer<FILE> __stream, ffi.Pointer<fpos_t> __pos);

@ffi.Native<ffi.Int Function(ffi.Pointer<FILE>, ffi.Pointer<fpos_t>)>()
external int fsetpos(ffi.Pointer<FILE> __stream, ffi.Pointer<fpos_t> __pos);

@ffi.Native<ffi.Void Function(ffi.Pointer<FILE>)>()
external void clearerr(ffi.Pointer<FILE> __stream);

@ffi.Native<ffi.Int Function(ffi.Pointer<FILE>)>()
external int feof(ffi.Pointer<FILE> __stream);

@ffi.Native<ffi.Int Function(ffi.Pointer<FILE>)>()
external int ferror(ffi.Pointer<FILE> __stream);

@ffi.Native<ffi.Void Function(ffi.Pointer<FILE>)>()
external void clearerr_unlocked(ffi.Pointer<FILE> __stream);

@ffi.Native<ffi.Int Function(ffi.Pointer<FILE>)>()
external int feof_unlocked(ffi.Pointer<FILE> __stream);

@ffi.Native<ffi.Int Function(ffi.Pointer<FILE>)>()
external int ferror_unlocked(ffi.Pointer<FILE> __stream);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Char>)>()
external void perror(ffi.Pointer<ffi.Char> __s);

@ffi.Native<ffi.Int Function(ffi.Pointer<FILE>)>()
external int fileno(ffi.Pointer<FILE> __stream);

@ffi.Native<ffi.Int Function(ffi.Pointer<FILE>)>()
external int fileno_unlocked(ffi.Pointer<FILE> __stream);

@ffi.Native<ffi.Int Function(ffi.Pointer<FILE>)>()
external int pclose(ffi.Pointer<FILE> __stream);

@ffi.Native<
  ffi.Pointer<FILE> Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
>()
external ffi.Pointer<FILE> popen(
  ffi.Pointer<ffi.Char> __command,
  ffi.Pointer<ffi.Char> __modes,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>()
external ffi.Pointer<ffi.Char> ctermid(ffi.Pointer<ffi.Char> __s);

@ffi.Native<ffi.Void Function(ffi.Pointer<FILE>)>()
external void flockfile(ffi.Pointer<FILE> __stream);

@ffi.Native<ffi.Int Function(ffi.Pointer<FILE>)>()
external int ftrylockfile(ffi.Pointer<FILE> __stream);

@ffi.Native<ffi.Void Function(ffi.Pointer<FILE>)>()
external void funlockfile(ffi.Pointer<FILE> __stream);

@ffi.Native<ffi.Int Function(ffi.Pointer<FILE>)>()
external int __uflow(ffi.Pointer<FILE> arg0);

@ffi.Native<ffi.Int Function(ffi.Pointer<FILE>, ffi.Int)>()
external int __overflow(ffi.Pointer<FILE> arg0, int arg1);

@ffi.Native<ffi.Int Function(ffi.Double)>()
external int __fpclassify(double __value);

@ffi.Native<ffi.Int Function(ffi.Double)>()
external int __signbit(double __value);

@ffi.Native<ffi.Int Function(ffi.Double)>()
external int __isinf(double __value);

@ffi.Native<ffi.Int Function(ffi.Double)>()
external int __finite(double __value);

@ffi.Native<ffi.Int Function(ffi.Double)>()
external int __isnan(double __value);

@ffi.Native<ffi.Int Function(ffi.Double, ffi.Double)>()
external int __iseqsig(double __x, double __y);

@ffi.Native<ffi.Int Function(ffi.Double)>()
external int __issignaling(double __value);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double acos(double __x);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double __acos(double __x);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double asin(double __x);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double __asin(double __x);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double atan(double __x);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double __atan(double __x);

@ffi.Native<ffi.Double Function(ffi.Double, ffi.Double)>()
external double atan2(double __y, double __x);

@ffi.Native<ffi.Double Function(ffi.Double, ffi.Double)>()
external double __atan2(double __y, double __x);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double cos(double __x);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double __cos(double __x);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double sin(double __x);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double __sin(double __x);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double tan(double __x);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double __tan(double __x);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double cosh(double __x);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double __cosh(double __x);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double sinh(double __x);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double __sinh(double __x);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double tanh(double __x);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double __tanh(double __x);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double acosh(double __x);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double __acosh(double __x);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double asinh(double __x);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double __asinh(double __x);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double atanh(double __x);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double __atanh(double __x);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double exp(double __x);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double __exp(double __x);

@ffi.Native<ffi.Double Function(ffi.Double, ffi.Pointer<ffi.Int>)>()
external double frexp(double __x, ffi.Pointer<ffi.Int> __exponent);

@ffi.Native<ffi.Double Function(ffi.Double, ffi.Pointer<ffi.Int>)>()
external double __frexp(double __x, ffi.Pointer<ffi.Int> __exponent);

@ffi.Native<ffi.Double Function(ffi.Double, ffi.Int)>()
external double ldexp(double __x, int __exponent);

@ffi.Native<ffi.Double Function(ffi.Double, ffi.Int)>()
external double __ldexp(double __x, int __exponent);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double log(double __x);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double __log(double __x);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double log10(double __x);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double __log10(double __x);

@ffi.Native<ffi.Double Function(ffi.Double, ffi.Pointer<ffi.Double>)>()
external double modf(double __x, ffi.Pointer<ffi.Double> __iptr);

@ffi.Native<ffi.Double Function(ffi.Double, ffi.Pointer<ffi.Double>)>()
external double __modf(double __x, ffi.Pointer<ffi.Double> __iptr);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double expm1(double __x);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double __expm1(double __x);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double log1p(double __x);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double __log1p(double __x);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double logb(double __x);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double __logb(double __x);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double exp2(double __x);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double __exp2(double __x);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double log2(double __x);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double __log2(double __x);

@ffi.Native<ffi.Double Function(ffi.Double, ffi.Double)>()
external double pow(double __x, double __y);

@ffi.Native<ffi.Double Function(ffi.Double, ffi.Double)>()
external double __pow(double __x, double __y);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double sqrt(double __x);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double __sqrt(double __x);

@ffi.Native<ffi.Double Function(ffi.Double, ffi.Double)>()
external double hypot(double __x, double __y);

@ffi.Native<ffi.Double Function(ffi.Double, ffi.Double)>()
external double __hypot(double __x, double __y);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double cbrt(double __x);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double __cbrt(double __x);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double ceil(double __x);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double fabs(double __x);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double floor(double __x);

@ffi.Native<ffi.Double Function(ffi.Double, ffi.Double)>()
external double fmod(double __x, double __y);

@ffi.Native<ffi.Double Function(ffi.Double, ffi.Double)>()
external double __fmod(double __x, double __y);

@ffi.Native<ffi.Int Function(ffi.Double)>()
external int isinf(double __value);

@ffi.Native<ffi.Int Function(ffi.Double)>()
external int finite(double __value);

@ffi.Native<ffi.Double Function(ffi.Double, ffi.Double)>()
external double drem(double __x, double __y);

@ffi.Native<ffi.Double Function(ffi.Double, ffi.Double)>()
external double __drem(double __x, double __y);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double significand(double __x);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double __significand(double __x);

@ffi.Native<ffi.Double Function(ffi.Double, ffi.Double)>()
external double copysign(double __x, double __y);

@ffi.Native<ffi.Double Function(ffi.Pointer<ffi.Char>)>()
external double nan(ffi.Pointer<ffi.Char> __tagb);

@ffi.Native<ffi.Double Function(ffi.Pointer<ffi.Char>)>()
external double __nan(ffi.Pointer<ffi.Char> __tagb);

@ffi.Native<ffi.Int Function(ffi.Double)>()
external int isnan(double __value);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double j0(double arg0);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double __j0(double arg0);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double j1(double arg0);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double __j1(double arg0);

@ffi.Native<ffi.Double Function(ffi.Int, ffi.Double)>()
external double jn(int arg0, double arg1);

@ffi.Native<ffi.Double Function(ffi.Int, ffi.Double)>()
external double __jn(int arg0, double arg1);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double y0(double arg0);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double __y0(double arg0);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double y1(double arg0);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double __y1(double arg0);

@ffi.Native<ffi.Double Function(ffi.Int, ffi.Double)>()
external double yn(int arg0, double arg1);

@ffi.Native<ffi.Double Function(ffi.Int, ffi.Double)>()
external double __yn(int arg0, double arg1);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double erf(double arg0);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double __erf(double arg0);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double erfc(double arg0);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double __erfc(double arg0);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double lgamma(double arg0);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double __lgamma(double arg0);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double tgamma(double arg0);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double __tgamma(double arg0);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double gamma(double arg0);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double __gamma(double arg0);

@ffi.Native<ffi.Double Function(ffi.Double, ffi.Pointer<ffi.Int>)>()
external double lgamma_r(double arg0, ffi.Pointer<ffi.Int> __signgamp);

@ffi.Native<ffi.Double Function(ffi.Double, ffi.Pointer<ffi.Int>)>()
external double __lgamma_r(double arg0, ffi.Pointer<ffi.Int> __signgamp);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double rint(double __x);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double __rint(double __x);

@ffi.Native<ffi.Double Function(ffi.Double, ffi.Double)>()
external double nextafter(double __x, double __y);

@ffi.Native<ffi.Double Function(ffi.Double, ffi.Double)>()
external double __nextafter(double __x, double __y);

@ffi.Native<ffi.Double Function(ffi.Double, ffi.Double)>()
external double remainder(double __x, double __y);

@ffi.Native<ffi.Double Function(ffi.Double, ffi.Double)>()
external double __remainder(double __x, double __y);

@ffi.Native<ffi.Double Function(ffi.Double, ffi.Int)>()
external double scalbn(double __x, int __n);

@ffi.Native<ffi.Double Function(ffi.Double, ffi.Int)>()
external double __scalbn(double __x, int __n);

@ffi.Native<ffi.Int Function(ffi.Double)>()
external int ilogb(double __x);

@ffi.Native<ffi.Int Function(ffi.Double)>()
external int __ilogb(double __x);

@ffi.Native<ffi.Double Function(ffi.Double, ffi.Long)>()
external double scalbln(double __x, int __n);

@ffi.Native<ffi.Double Function(ffi.Double, ffi.Long)>()
external double __scalbln(double __x, int __n);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double nearbyint(double __x);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double __nearbyint(double __x);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double round(double __x);

@ffi.Native<ffi.Double Function(ffi.Double)>()
external double trunc(double __x);

@ffi.Native<ffi.Double Function(ffi.Double, ffi.Double, ffi.Pointer<ffi.Int>)>()
external double remquo(double __x, double __y, ffi.Pointer<ffi.Int> __quo);

@ffi.Native<ffi.Double Function(ffi.Double, ffi.Double, ffi.Pointer<ffi.Int>)>()
external double __remquo(double __x, double __y, ffi.Pointer<ffi.Int> __quo);

@ffi.Native<ffi.Long Function(ffi.Double)>()
external int lrint(double __x);

@ffi.Native<ffi.Long Function(ffi.Double)>()
external int __lrint(double __x);

@ffi.Native<ffi.LongLong Function(ffi.Double)>()
external int llrint(double __x);

@ffi.Native<ffi.LongLong Function(ffi.Double)>()
external int __llrint(double __x);

@ffi.Native<ffi.Long Function(ffi.Double)>()
external int lround(double __x);

@ffi.Native<ffi.Long Function(ffi.Double)>()
external int __lround(double __x);

@ffi.Native<ffi.LongLong Function(ffi.Double)>()
external int llround(double __x);

@ffi.Native<ffi.LongLong Function(ffi.Double)>()
external int __llround(double __x);

@ffi.Native<ffi.Double Function(ffi.Double, ffi.Double)>()
external double fdim(double __x, double __y);

@ffi.Native<ffi.Double Function(ffi.Double, ffi.Double)>()
external double __fdim(double __x, double __y);

@ffi.Native<ffi.Double Function(ffi.Double, ffi.Double)>()
external double fmax(double __x, double __y);

@ffi.Native<ffi.Double Function(ffi.Double, ffi.Double)>()
external double fmin(double __x, double __y);

@ffi.Native<ffi.Double Function(ffi.Double, ffi.Double, ffi.Double)>()
external double fma(double __x, double __y, double __z);

@ffi.Native<ffi.Double Function(ffi.Double, ffi.Double, ffi.Double)>()
external double __fma(double __x, double __y, double __z);

@ffi.Native<ffi.Double Function(ffi.Double, ffi.Double)>()
external double scalb(double __x, double __n);

@ffi.Native<ffi.Double Function(ffi.Double, ffi.Double)>()
external double __scalb(double __x, double __n);

@ffi.Native<ffi.Int Function(ffi.Float)>()
external int __fpclassifyf(double __value);

@ffi.Native<ffi.Int Function(ffi.Float)>()
external int __signbitf(double __value);

@ffi.Native<ffi.Int Function(ffi.Float)>()
external int __isinff(double __value);

@ffi.Native<ffi.Int Function(ffi.Float)>()
external int __finitef(double __value);

@ffi.Native<ffi.Int Function(ffi.Float)>()
external int __isnanf(double __value);

@ffi.Native<ffi.Int Function(ffi.Float, ffi.Float)>()
external int __iseqsigf(double __x, double __y);

@ffi.Native<ffi.Int Function(ffi.Float)>()
external int __issignalingf(double __value);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double acosf(double __x);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double __acosf(double __x);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double asinf(double __x);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double __asinf(double __x);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double atanf(double __x);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double __atanf(double __x);

@ffi.Native<ffi.Float Function(ffi.Float, ffi.Float)>()
external double atan2f(double __y, double __x);

@ffi.Native<ffi.Float Function(ffi.Float, ffi.Float)>()
external double __atan2f(double __y, double __x);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double cosf(double __x);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double __cosf(double __x);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double sinf(double __x);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double __sinf(double __x);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double tanf(double __x);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double __tanf(double __x);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double coshf(double __x);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double __coshf(double __x);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double sinhf(double __x);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double __sinhf(double __x);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double tanhf(double __x);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double __tanhf(double __x);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double acoshf(double __x);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double __acoshf(double __x);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double asinhf(double __x);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double __asinhf(double __x);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double atanhf(double __x);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double __atanhf(double __x);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double expf(double __x);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double __expf(double __x);

@ffi.Native<ffi.Float Function(ffi.Float, ffi.Pointer<ffi.Int>)>()
external double frexpf(double __x, ffi.Pointer<ffi.Int> __exponent);

@ffi.Native<ffi.Float Function(ffi.Float, ffi.Pointer<ffi.Int>)>()
external double __frexpf(double __x, ffi.Pointer<ffi.Int> __exponent);

@ffi.Native<ffi.Float Function(ffi.Float, ffi.Int)>()
external double ldexpf(double __x, int __exponent);

@ffi.Native<ffi.Float Function(ffi.Float, ffi.Int)>()
external double __ldexpf(double __x, int __exponent);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double logf(double __x);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double __logf(double __x);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double log10f(double __x);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double __log10f(double __x);

@ffi.Native<ffi.Float Function(ffi.Float, ffi.Pointer<ffi.Float>)>()
external double modff(double __x, ffi.Pointer<ffi.Float> __iptr);

@ffi.Native<ffi.Float Function(ffi.Float, ffi.Pointer<ffi.Float>)>()
external double __modff(double __x, ffi.Pointer<ffi.Float> __iptr);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double expm1f(double __x);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double __expm1f(double __x);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double log1pf(double __x);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double __log1pf(double __x);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double logbf(double __x);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double __logbf(double __x);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double exp2f(double __x);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double __exp2f(double __x);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double log2f(double __x);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double __log2f(double __x);

@ffi.Native<ffi.Float Function(ffi.Float, ffi.Float)>()
external double powf(double __x, double __y);

@ffi.Native<ffi.Float Function(ffi.Float, ffi.Float)>()
external double __powf(double __x, double __y);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double sqrtf(double __x);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double __sqrtf(double __x);

@ffi.Native<ffi.Float Function(ffi.Float, ffi.Float)>()
external double hypotf(double __x, double __y);

@ffi.Native<ffi.Float Function(ffi.Float, ffi.Float)>()
external double __hypotf(double __x, double __y);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double cbrtf(double __x);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double __cbrtf(double __x);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double ceilf(double __x);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double fabsf(double __x);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double floorf(double __x);

@ffi.Native<ffi.Float Function(ffi.Float, ffi.Float)>()
external double fmodf(double __x, double __y);

@ffi.Native<ffi.Float Function(ffi.Float, ffi.Float)>()
external double __fmodf(double __x, double __y);

@ffi.Native<ffi.Int Function(ffi.Float)>()
external int isinff(double __value);

@ffi.Native<ffi.Int Function(ffi.Float)>()
external int finitef(double __value);

@ffi.Native<ffi.Float Function(ffi.Float, ffi.Float)>()
external double dremf(double __x, double __y);

@ffi.Native<ffi.Float Function(ffi.Float, ffi.Float)>()
external double __dremf(double __x, double __y);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double significandf(double __x);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double __significandf(double __x);

@ffi.Native<ffi.Float Function(ffi.Float, ffi.Float)>()
external double copysignf(double __x, double __y);

@ffi.Native<ffi.Float Function(ffi.Pointer<ffi.Char>)>()
external double nanf(ffi.Pointer<ffi.Char> __tagb);

@ffi.Native<ffi.Float Function(ffi.Pointer<ffi.Char>)>()
external double __nanf(ffi.Pointer<ffi.Char> __tagb);

@ffi.Native<ffi.Int Function(ffi.Float)>()
external int isnanf(double __value);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double j0f(double arg0);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double __j0f(double arg0);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double j1f(double arg0);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double __j1f(double arg0);

@ffi.Native<ffi.Float Function(ffi.Int, ffi.Float)>()
external double jnf(int arg0, double arg1);

@ffi.Native<ffi.Float Function(ffi.Int, ffi.Float)>()
external double __jnf(int arg0, double arg1);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double y0f(double arg0);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double __y0f(double arg0);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double y1f(double arg0);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double __y1f(double arg0);

@ffi.Native<ffi.Float Function(ffi.Int, ffi.Float)>()
external double ynf(int arg0, double arg1);

@ffi.Native<ffi.Float Function(ffi.Int, ffi.Float)>()
external double __ynf(int arg0, double arg1);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double erff(double arg0);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double __erff(double arg0);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double erfcf(double arg0);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double __erfcf(double arg0);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double lgammaf(double arg0);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double __lgammaf(double arg0);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double tgammaf(double arg0);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double __tgammaf(double arg0);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double gammaf(double arg0);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double __gammaf(double arg0);

@ffi.Native<ffi.Float Function(ffi.Float, ffi.Pointer<ffi.Int>)>()
external double lgammaf_r(double arg0, ffi.Pointer<ffi.Int> __signgamp);

@ffi.Native<ffi.Float Function(ffi.Float, ffi.Pointer<ffi.Int>)>()
external double __lgammaf_r(double arg0, ffi.Pointer<ffi.Int> __signgamp);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double rintf(double __x);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double __rintf(double __x);

@ffi.Native<ffi.Float Function(ffi.Float, ffi.Float)>()
external double nextafterf(double __x, double __y);

@ffi.Native<ffi.Float Function(ffi.Float, ffi.Float)>()
external double __nextafterf(double __x, double __y);

@ffi.Native<ffi.Float Function(ffi.Float, ffi.Float)>()
external double remainderf(double __x, double __y);

@ffi.Native<ffi.Float Function(ffi.Float, ffi.Float)>()
external double __remainderf(double __x, double __y);

@ffi.Native<ffi.Float Function(ffi.Float, ffi.Int)>()
external double scalbnf(double __x, int __n);

@ffi.Native<ffi.Float Function(ffi.Float, ffi.Int)>()
external double __scalbnf(double __x, int __n);

@ffi.Native<ffi.Int Function(ffi.Float)>()
external int ilogbf(double __x);

@ffi.Native<ffi.Int Function(ffi.Float)>()
external int __ilogbf(double __x);

@ffi.Native<ffi.Float Function(ffi.Float, ffi.Long)>()
external double scalblnf(double __x, int __n);

@ffi.Native<ffi.Float Function(ffi.Float, ffi.Long)>()
external double __scalblnf(double __x, int __n);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double nearbyintf(double __x);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double __nearbyintf(double __x);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double roundf(double __x);

@ffi.Native<ffi.Float Function(ffi.Float)>()
external double truncf(double __x);

@ffi.Native<ffi.Float Function(ffi.Float, ffi.Float, ffi.Pointer<ffi.Int>)>()
external double remquof(double __x, double __y, ffi.Pointer<ffi.Int> __quo);

@ffi.Native<ffi.Float Function(ffi.Float, ffi.Float, ffi.Pointer<ffi.Int>)>()
external double __remquof(double __x, double __y, ffi.Pointer<ffi.Int> __quo);

@ffi.Native<ffi.Long Function(ffi.Float)>()
external int lrintf(double __x);

@ffi.Native<ffi.Long Function(ffi.Float)>()
external int __lrintf(double __x);

@ffi.Native<ffi.LongLong Function(ffi.Float)>()
external int llrintf(double __x);

@ffi.Native<ffi.LongLong Function(ffi.Float)>()
external int __llrintf(double __x);

@ffi.Native<ffi.Long Function(ffi.Float)>()
external int lroundf(double __x);

@ffi.Native<ffi.Long Function(ffi.Float)>()
external int __lroundf(double __x);

@ffi.Native<ffi.LongLong Function(ffi.Float)>()
external int llroundf(double __x);

@ffi.Native<ffi.LongLong Function(ffi.Float)>()
external int __llroundf(double __x);

@ffi.Native<ffi.Float Function(ffi.Float, ffi.Float)>()
external double fdimf(double __x, double __y);

@ffi.Native<ffi.Float Function(ffi.Float, ffi.Float)>()
external double __fdimf(double __x, double __y);

@ffi.Native<ffi.Float Function(ffi.Float, ffi.Float)>()
external double fmaxf(double __x, double __y);

@ffi.Native<ffi.Float Function(ffi.Float, ffi.Float)>()
external double fminf(double __x, double __y);

@ffi.Native<ffi.Float Function(ffi.Float, ffi.Float, ffi.Float)>()
external double fmaf(double __x, double __y, double __z);

@ffi.Native<ffi.Float Function(ffi.Float, ffi.Float, ffi.Float)>()
external double __fmaf(double __x, double __y, double __z);

@ffi.Native<ffi.Float Function(ffi.Float, ffi.Float)>()
external double scalbf(double __x, double __n);

@ffi.Native<ffi.Float Function(ffi.Float, ffi.Float)>()
external double __scalbf(double __x, double __n);

@ffi.Native<ffi.Int>()
external int signgam;

@ffi.Native<
  ffi.Pointer<ffi.Void> Function(
    ffi.Pointer<ffi.Void>,
    ffi.Pointer<ffi.Void>,
    ffi.Size,
  )
>()
external ffi.Pointer<ffi.Void> memcpy(
  ffi.Pointer<ffi.Void> __dest,
  ffi.Pointer<ffi.Void> __src,
  int __n,
);

@ffi.Native<
  ffi.Pointer<ffi.Void> Function(
    ffi.Pointer<ffi.Void>,
    ffi.Pointer<ffi.Void>,
    ffi.Size,
  )
>()
external ffi.Pointer<ffi.Void> memmove(
  ffi.Pointer<ffi.Void> __dest,
  ffi.Pointer<ffi.Void> __src,
  int __n,
);

@ffi.Native<
  ffi.Pointer<ffi.Void> Function(
    ffi.Pointer<ffi.Void>,
    ffi.Pointer<ffi.Void>,
    ffi.Int,
    ffi.Size,
  )
>()
external ffi.Pointer<ffi.Void> memccpy(
  ffi.Pointer<ffi.Void> __dest,
  ffi.Pointer<ffi.Void> __src,
  int __c,
  int __n,
);

@ffi.Native<
  ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>, ffi.Int, ffi.Size)
>()
external ffi.Pointer<ffi.Void> memset(
  ffi.Pointer<ffi.Void> __s,
  int __c,
  int __n,
);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>, ffi.Size)
>()
external int memcmp(
  ffi.Pointer<ffi.Void> __s1,
  ffi.Pointer<ffi.Void> __s2,
  int __n,
);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>, ffi.Size)
>()
external int __memcmpeq(
  ffi.Pointer<ffi.Void> __s1,
  ffi.Pointer<ffi.Void> __s2,
  int __n,
);

@ffi.Native<
  ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>, ffi.Int, ffi.Size)
>()
external ffi.Pointer<ffi.Void> memchr(
  ffi.Pointer<ffi.Void> __s,
  int __c,
  int __n,
);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
>()
external ffi.Pointer<ffi.Char> strcpy(
  ffi.Pointer<ffi.Char> __dest,
  ffi.Pointer<ffi.Char> __src,
);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Size,
  )
>()
external ffi.Pointer<ffi.Char> strncpy(
  ffi.Pointer<ffi.Char> __dest,
  ffi.Pointer<ffi.Char> __src,
  int __n,
);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
>()
external ffi.Pointer<ffi.Char> strcat(
  ffi.Pointer<ffi.Char> __dest,
  ffi.Pointer<ffi.Char> __src,
);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Size,
  )
>()
external ffi.Pointer<ffi.Char> strncat(
  ffi.Pointer<ffi.Char> __dest,
  ffi.Pointer<ffi.Char> __src,
  int __n,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>()
external int strcmp(ffi.Pointer<ffi.Char> __s1, ffi.Pointer<ffi.Char> __s2);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Size)
>()
external int strncmp(
  ffi.Pointer<ffi.Char> __s1,
  ffi.Pointer<ffi.Char> __s2,
  int __n,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>()
external int strcoll(ffi.Pointer<ffi.Char> __s1, ffi.Pointer<ffi.Char> __s2);

@ffi.Native<
  ffi.UnsignedLong Function(
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Size,
  )
>()
external int strxfrm(
  ffi.Pointer<ffi.Char> __dest,
  ffi.Pointer<ffi.Char> __src,
  int __n,
);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, locale_t)
>()
external int strcoll_l(
  ffi.Pointer<ffi.Char> __s1,
  ffi.Pointer<ffi.Char> __s2,
  locale_t __l,
);

@ffi.Native<
  ffi.Size Function(
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Size,
    locale_t,
  )
>()
external int strxfrm_l(
  ffi.Pointer<ffi.Char> __dest,
  ffi.Pointer<ffi.Char> __src,
  int __n,
  locale_t __l,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>()
external ffi.Pointer<ffi.Char> strdup(ffi.Pointer<ffi.Char> __s);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>, ffi.Size)>()
external ffi.Pointer<ffi.Char> strndup(ffi.Pointer<ffi.Char> __string, int __n);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>, ffi.Int)>()
external ffi.Pointer<ffi.Char> strchr(ffi.Pointer<ffi.Char> __s, int __c);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>, ffi.Int)>()
external ffi.Pointer<ffi.Char> strrchr(ffi.Pointer<ffi.Char> __s, int __c);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>, ffi.Int)>()
external ffi.Pointer<ffi.Char> strchrnul(ffi.Pointer<ffi.Char> __s, int __c);

@ffi.Native<
  ffi.UnsignedLong Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
>()
external int strcspn(ffi.Pointer<ffi.Char> __s, ffi.Pointer<ffi.Char> __reject);

@ffi.Native<
  ffi.UnsignedLong Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
>()
external int strspn(ffi.Pointer<ffi.Char> __s, ffi.Pointer<ffi.Char> __accept);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
>()
external ffi.Pointer<ffi.Char> strpbrk(
  ffi.Pointer<ffi.Char> __s,
  ffi.Pointer<ffi.Char> __accept,
);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
>()
external ffi.Pointer<ffi.Char> strstr(
  ffi.Pointer<ffi.Char> __haystack,
  ffi.Pointer<ffi.Char> __needle,
);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
>()
external ffi.Pointer<ffi.Char> strtok(
  ffi.Pointer<ffi.Char> __s,
  ffi.Pointer<ffi.Char> __delim,
);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
  )
>()
external ffi.Pointer<ffi.Char> __strtok_r(
  ffi.Pointer<ffi.Char> __s,
  ffi.Pointer<ffi.Char> __delim,
  ffi.Pointer<ffi.Pointer<ffi.Char>> __save_ptr,
);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
  )
>()
external ffi.Pointer<ffi.Char> strtok_r(
  ffi.Pointer<ffi.Char> __s,
  ffi.Pointer<ffi.Char> __delim,
  ffi.Pointer<ffi.Pointer<ffi.Char>> __save_ptr,
);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
>()
external ffi.Pointer<ffi.Char> strcasestr(
  ffi.Pointer<ffi.Char> __haystack,
  ffi.Pointer<ffi.Char> __needle,
);

@ffi.Native<
  ffi.Pointer<ffi.Void> Function(
    ffi.Pointer<ffi.Void>,
    ffi.Size,
    ffi.Pointer<ffi.Void>,
    ffi.Size,
  )
>()
external ffi.Pointer<ffi.Void> memmem(
  ffi.Pointer<ffi.Void> __haystack,
  int __haystacklen,
  ffi.Pointer<ffi.Void> __needle,
  int __needlelen,
);

@ffi.Native<
  ffi.Pointer<ffi.Void> Function(
    ffi.Pointer<ffi.Void>,
    ffi.Pointer<ffi.Void>,
    ffi.Size,
  )
>()
external ffi.Pointer<ffi.Void> __mempcpy(
  ffi.Pointer<ffi.Void> __dest,
  ffi.Pointer<ffi.Void> __src,
  int __n,
);

@ffi.Native<
  ffi.Pointer<ffi.Void> Function(
    ffi.Pointer<ffi.Void>,
    ffi.Pointer<ffi.Void>,
    ffi.Size,
  )
>()
external ffi.Pointer<ffi.Void> mempcpy(
  ffi.Pointer<ffi.Void> __dest,
  ffi.Pointer<ffi.Void> __src,
  int __n,
);

@ffi.Native<ffi.UnsignedLong Function(ffi.Pointer<ffi.Char>)>()
external int strlen(ffi.Pointer<ffi.Char> __s);

@ffi.Native<ffi.Size Function(ffi.Pointer<ffi.Char>, ffi.Size)>()
external int strnlen(ffi.Pointer<ffi.Char> __string, int __maxlen);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Int)>()
external ffi.Pointer<ffi.Char> strerror(int __errnum);

@ffi.Native<ffi.Int Function(ffi.Int, ffi.Pointer<ffi.Char>, ffi.Size)>()
external int strerror_r(
  int __errnum,
  ffi.Pointer<ffi.Char> __buf,
  int __buflen,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Int, locale_t)>()
external ffi.Pointer<ffi.Char> strerror_l(int __errnum, locale_t __l);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>, ffi.Size)
>()
external int bcmp(
  ffi.Pointer<ffi.Void> __s1,
  ffi.Pointer<ffi.Void> __s2,
  int __n,
);

@ffi.Native<
  ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>, ffi.Size)
>()
external void bcopy(
  ffi.Pointer<ffi.Void> __src,
  ffi.Pointer<ffi.Void> __dest,
  int __n,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Size)>()
external void bzero(ffi.Pointer<ffi.Void> __s, int __n);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>, ffi.Int)>()
external ffi.Pointer<ffi.Char> index(ffi.Pointer<ffi.Char> __s, int __c);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>, ffi.Int)>()
external ffi.Pointer<ffi.Char> rindex(ffi.Pointer<ffi.Char> __s, int __c);

@ffi.Native<ffi.Int Function(ffi.Int)>()
external int ffs(int __i);

@ffi.Native<ffi.Int Function(ffi.Long)>()
external int ffsl(int __l);

@ffi.Native<ffi.Int Function(ffi.LongLong)>()
external int ffsll(int __ll);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>()
external int strcasecmp(ffi.Pointer<ffi.Char> __s1, ffi.Pointer<ffi.Char> __s2);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Size)
>()
external int strncasecmp(
  ffi.Pointer<ffi.Char> __s1,
  ffi.Pointer<ffi.Char> __s2,
  int __n,
);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, locale_t)
>()
external int strcasecmp_l(
  ffi.Pointer<ffi.Char> __s1,
  ffi.Pointer<ffi.Char> __s2,
  locale_t __loc,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Size,
    locale_t,
  )
>()
external int strncasecmp_l(
  ffi.Pointer<ffi.Char> __s1,
  ffi.Pointer<ffi.Char> __s2,
  int __n,
  locale_t __loc,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Size)>()
external void explicit_bzero(ffi.Pointer<ffi.Void> __s, int __n);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
    ffi.Pointer<ffi.Char>,
  )
>()
external ffi.Pointer<ffi.Char> strsep(
  ffi.Pointer<ffi.Pointer<ffi.Char>> __stringp,
  ffi.Pointer<ffi.Char> __delim,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Int)>()
external ffi.Pointer<ffi.Char> strsignal(int __sig);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
>()
external ffi.Pointer<ffi.Char> __stpcpy(
  ffi.Pointer<ffi.Char> __dest,
  ffi.Pointer<ffi.Char> __src,
);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
>()
external ffi.Pointer<ffi.Char> stpcpy(
  ffi.Pointer<ffi.Char> __dest,
  ffi.Pointer<ffi.Char> __src,
);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Size,
  )
>()
external ffi.Pointer<ffi.Char> __stpncpy(
  ffi.Pointer<ffi.Char> __dest,
  ffi.Pointer<ffi.Char> __src,
  int __n,
);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Size,
  )
>()
external ffi.Pointer<ffi.Char> stpncpy(
  ffi.Pointer<ffi.Char> __dest,
  ffi.Pointer<ffi.Char> __src,
  int __n,
);

@ffi.Native<
  ffi.Size Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Size)
>()
external int strlcpy(
  ffi.Pointer<ffi.Char> __dest,
  ffi.Pointer<ffi.Char> __src,
  int __n,
);

@ffi.Native<
  ffi.Size Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Size)
>()
external int strlcat(
  ffi.Pointer<ffi.Char> __dest,
  ffi.Pointer<ffi.Char> __src,
  int __n,
);

/// kiss_fft_alloc
///
/// Initialize a FFT (or IFFT) algorithm's cfg/state buffer.
///
/// typical usage:      kiss_fft_cfg mycfg=kiss_fft_alloc(1024,0,NULL,NULL);
///
/// The return value from fft_alloc is a cfg buffer used internally
/// by the fft routine or NULL.
///
/// If lenmem is NULL, then kiss_fft_alloc will allocate a cfg buffer using malloc.
/// The returned value should be free()d when done to avoid memory leaks.
///
/// The state can be placed in a user supplied buffer 'mem':
/// If lenmem is not NULL and mem is not NULL and *lenmem is large enough,
/// then the function places the cfg in mem and the size used in *lenmem
/// and returns mem.
///
/// If lenmem is not NULL and ( mem is NULL or *lenmem is not large enough),
/// then the function returns NULL and places the minimum cfg
/// buffer size in *lenmem.
@ffi.Native<
  kiss_fft_cfg Function(
    ffi.Int,
    ffi.Int,
    ffi.Pointer<ffi.Void>,
    ffi.Pointer<ffi.Size>,
  )
>()
external kiss_fft_cfg kiss_fft_alloc(
  int nfft,
  int inverse_fft,
  ffi.Pointer<ffi.Void> mem,
  ffi.Pointer<ffi.Size> lenmem,
);

/// kiss_fft(cfg,in_out_buf)
///
/// Perform an FFT on a complex input buffer.
/// for a forward FFT,
/// fin should be  f[0] , f[1] , ... ,f[nfft-1]
/// fout will be   F[0] , F[1] , ... ,F[nfft-1]
/// Note that each element is complex and can be accessed like
/// f[k].r and f[k].i
@ffi.Native<
  ffi.Void Function(
    kiss_fft_cfg,
    ffi.Pointer<kiss_fft_cpx>,
    ffi.Pointer<kiss_fft_cpx>,
  )
>()
external void kiss_fft(
  kiss_fft_cfg cfg,
  ffi.Pointer<kiss_fft_cpx> fin,
  ffi.Pointer<kiss_fft_cpx> fout,
);

/// A more generic version of the above function. It reads its input from every Nth sample.
@ffi.Native<
  ffi.Void Function(
    kiss_fft_cfg,
    ffi.Pointer<kiss_fft_cpx>,
    ffi.Pointer<kiss_fft_cpx>,
    ffi.Int,
  )
>()
external void kiss_fft_stride(
  kiss_fft_cfg cfg,
  ffi.Pointer<kiss_fft_cpx> fin,
  ffi.Pointer<kiss_fft_cpx> fout,
  int fin_stride,
);

/// Cleans up some memory that gets managed internally. Not necessary to call, but it might clean up
/// your compiler output to call this before you exit.
@ffi.Native<ffi.Void Function()>()
external void kiss_fft_cleanup();

/// Returns the smallest integer k, such that k>=n and k has only "fast" factors (2,3,5)
@ffi.Native<ffi.Int Function(ffi.Int)>()
external int kiss_fft_next_fast_size(int n);

@ffi.Native<
  kiss_fftr_cfg Function(
    ffi.Int,
    ffi.Int,
    ffi.Pointer<ffi.Void>,
    ffi.Pointer<ffi.Size>,
  )
>()
external kiss_fftr_cfg kiss_fftr_alloc(
  int nfft,
  int inverse_fft,
  ffi.Pointer<ffi.Void> mem,
  ffi.Pointer<ffi.Size> lenmem,
);

/// nfft must be even
///
/// If you don't care to allocate space, use mem = lenmem = NULL
@ffi.Native<
  ffi.Void Function(
    kiss_fftr_cfg,
    ffi.Pointer<ffi.Double>,
    ffi.Pointer<kiss_fft_cpx>,
  )
>()
external void kiss_fftr(
  kiss_fftr_cfg cfg,
  ffi.Pointer<ffi.Double> timedata,
  ffi.Pointer<kiss_fft_cpx> freqdata,
);

/// input timedata has nfft scalar points
/// output freqdata has nfft/2+1 complex points
@ffi.Native<
  ffi.Void Function(
    kiss_fftr_cfg,
    ffi.Pointer<kiss_fft_cpx>,
    ffi.Pointer<ffi.Double>,
  )
>()
external void kiss_fftri(
  kiss_fftr_cfg cfg,
  ffi.Pointer<kiss_fft_cpx> freqdata,
  ffi.Pointer<ffi.Double> timedata,
);

/// Natively sort a double precision float64 array of the specified size in-place.
/// Uses pure C-to-C callbacks via standard library qsort to prevent FFI boundary jumps.
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Double>, ffi.Int)>()
external void native_sort_double(ffi.Pointer<ffi.Double> array, int size);

/// Natively sort a single precision float32 array of the specified size in-place.
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Float>, ffi.Int)>()
external void native_sort_float(ffi.Pointer<ffi.Float> array, int size);

/// Natively sort an int64 array of the specified size in-place.
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.LongLong>, ffi.Int)>()
external void native_sort_int64(ffi.Pointer<ffi.LongLong> array, int size);

/// Natively sort an int32 array of the specified size in-place.
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Int>, ffi.Int)>()
external void native_sort_int32(ffi.Pointer<ffi.Int> array, int size);

typedef _Float32 = ffi.Float;
typedef Dart_Float32 = double;
typedef _Float64 = ffi.Double;
typedef Dart_Float64 = double;
typedef _Float32x = ffi.Double;
typedef Dart_Float32x = double;

final class div_t extends ffi.Struct {
  @ffi.Int()
  external int quot;

  @ffi.Int()
  external int rem;
}

final class ldiv_t extends ffi.Struct {
  @ffi.Long()
  external int quot;

  @ffi.Long()
  external int rem;
}

final class lldiv_t extends ffi.Struct {
  @ffi.LongLong()
  external int quot;

  @ffi.LongLong()
  external int rem;
}

typedef __u_char = ffi.UnsignedChar;
typedef Dart__u_char = int;
typedef __u_short = ffi.UnsignedShort;
typedef Dart__u_short = int;
typedef __u_int = ffi.UnsignedInt;
typedef Dart__u_int = int;
typedef __u_long = ffi.UnsignedLong;
typedef Dart__u_long = int;
typedef __int8_t = ffi.SignedChar;
typedef Dart__int8_t = int;
typedef __uint8_t = ffi.UnsignedChar;
typedef Dart__uint8_t = int;
typedef __int16_t = ffi.Short;
typedef Dart__int16_t = int;
typedef __uint16_t = ffi.UnsignedShort;
typedef Dart__uint16_t = int;
typedef __int32_t = ffi.Int;
typedef Dart__int32_t = int;
typedef __uint32_t = ffi.UnsignedInt;
typedef Dart__uint32_t = int;
typedef __int64_t = ffi.Long;
typedef Dart__int64_t = int;
typedef __uint64_t = ffi.UnsignedLong;
typedef Dart__uint64_t = int;
typedef __int_least8_t = __int8_t;
typedef __uint_least8_t = __uint8_t;
typedef __int_least16_t = __int16_t;
typedef __uint_least16_t = __uint16_t;
typedef __int_least32_t = __int32_t;
typedef __uint_least32_t = __uint32_t;
typedef __int_least64_t = __int64_t;
typedef __uint_least64_t = __uint64_t;
typedef __quad_t = ffi.Long;
typedef Dart__quad_t = int;
typedef __u_quad_t = ffi.UnsignedLong;
typedef Dart__u_quad_t = int;
typedef __intmax_t = ffi.Long;
typedef Dart__intmax_t = int;
typedef __uintmax_t = ffi.UnsignedLong;
typedef Dart__uintmax_t = int;
typedef __dev_t = ffi.UnsignedLong;
typedef Dart__dev_t = int;
typedef __uid_t = ffi.UnsignedInt;
typedef Dart__uid_t = int;
typedef __gid_t = ffi.UnsignedInt;
typedef Dart__gid_t = int;
typedef __ino_t = ffi.UnsignedLong;
typedef Dart__ino_t = int;
typedef __ino64_t = ffi.UnsignedLong;
typedef Dart__ino64_t = int;
typedef __mode_t = ffi.UnsignedInt;
typedef Dart__mode_t = int;
typedef __nlink_t = ffi.UnsignedLong;
typedef Dart__nlink_t = int;
typedef __off_t = ffi.Long;
typedef Dart__off_t = int;
typedef __off64_t = ffi.Long;
typedef Dart__off64_t = int;
typedef __pid_t = ffi.Int;
typedef Dart__pid_t = int;

final class __fsid_t extends ffi.Struct {
  @ffi.Array.multi([2])
  external ffi.Array<ffi.Int> __val;
}

typedef __clock_t = ffi.Long;
typedef Dart__clock_t = int;
typedef __rlim_t = ffi.UnsignedLong;
typedef Dart__rlim_t = int;
typedef __rlim64_t = ffi.UnsignedLong;
typedef Dart__rlim64_t = int;
typedef __id_t = ffi.UnsignedInt;
typedef Dart__id_t = int;
typedef __time_t = ffi.Long;
typedef Dart__time_t = int;
typedef __useconds_t = ffi.UnsignedInt;
typedef Dart__useconds_t = int;
typedef __suseconds_t = ffi.Long;
typedef Dart__suseconds_t = int;
typedef __suseconds64_t = ffi.Long;
typedef Dart__suseconds64_t = int;
typedef __daddr_t = ffi.Int;
typedef Dart__daddr_t = int;
typedef __key_t = ffi.Int;
typedef Dart__key_t = int;
typedef __clockid_t = ffi.Int;
typedef Dart__clockid_t = int;
typedef __timer_t = ffi.Pointer<ffi.Void>;
typedef __blksize_t = ffi.Long;
typedef Dart__blksize_t = int;
typedef __blkcnt_t = ffi.Long;
typedef Dart__blkcnt_t = int;
typedef __blkcnt64_t = ffi.Long;
typedef Dart__blkcnt64_t = int;
typedef __fsblkcnt_t = ffi.UnsignedLong;
typedef Dart__fsblkcnt_t = int;
typedef __fsblkcnt64_t = ffi.UnsignedLong;
typedef Dart__fsblkcnt64_t = int;
typedef __fsfilcnt_t = ffi.UnsignedLong;
typedef Dart__fsfilcnt_t = int;
typedef __fsfilcnt64_t = ffi.UnsignedLong;
typedef Dart__fsfilcnt64_t = int;
typedef __fsword_t = ffi.Long;
typedef Dart__fsword_t = int;
typedef __ssize_t = ffi.Long;
typedef Dart__ssize_t = int;
typedef __syscall_slong_t = ffi.Long;
typedef Dart__syscall_slong_t = int;
typedef __syscall_ulong_t = ffi.UnsignedLong;
typedef Dart__syscall_ulong_t = int;
typedef __loff_t = __off64_t;
typedef __caddr_t = ffi.Pointer<ffi.Char>;
typedef __intptr_t = ffi.Long;
typedef Dart__intptr_t = int;
typedef __socklen_t = ffi.UnsignedInt;
typedef Dart__socklen_t = int;
typedef __sig_atomic_t = ffi.Int;
typedef Dart__sig_atomic_t = int;
typedef u_char = __u_char;
typedef u_short = __u_short;
typedef u_int = __u_int;
typedef u_long = __u_long;
typedef quad_t = __quad_t;
typedef u_quad_t = __u_quad_t;
typedef fsid_t = __fsid_t;
typedef loff_t = __loff_t;
typedef ino_t = __ino_t;
typedef dev_t = __dev_t;
typedef gid_t = __gid_t;
typedef mode_t = __mode_t;
typedef nlink_t = __nlink_t;
typedef uid_t = __uid_t;
typedef off_t = __off_t;
typedef pid_t = __pid_t;
typedef id_t = __id_t;
typedef ssize_t = __ssize_t;
typedef daddr_t = __daddr_t;
typedef caddr_t = __caddr_t;
typedef key_t = __key_t;
typedef clock_t = __clock_t;
typedef clockid_t = __clockid_t;
typedef time_t = __time_t;
typedef timer_t = __timer_t;
typedef ulong = ffi.UnsignedLong;
typedef Dartulong = int;
typedef ushort = ffi.UnsignedShort;
typedef Dartushort = int;
typedef uint = ffi.UnsignedInt;
typedef Dartuint = int;
typedef u_int8_t = __uint8_t;
typedef u_int16_t = __uint16_t;
typedef u_int32_t = __uint32_t;
typedef u_int64_t = __uint64_t;
typedef register_t = ffi.Long;
typedef Dartregister_t = int;

final class __sigset_t extends ffi.Struct {
  @ffi.Array.multi([16])
  external ffi.Array<ffi.UnsignedLong> __val;
}

typedef sigset_t = __sigset_t;

final class timeval extends ffi.Struct {
  @__time_t()
  external int tv_sec;

  @__suseconds_t()
  external int tv_usec;
}

final class timespec extends ffi.Struct {
  @__time_t()
  external int tv_sec;

  @__syscall_slong_t()
  external int tv_nsec;
}

typedef suseconds_t = __suseconds_t;
typedef __fd_mask = ffi.Long;
typedef Dart__fd_mask = int;

final class fd_set extends ffi.Struct {
  @ffi.Array.multi([16])
  external ffi.Array<__fd_mask> __fds_bits;
}

typedef fd_mask = __fd_mask;
typedef blksize_t = __blksize_t;
typedef blkcnt_t = __blkcnt_t;
typedef fsblkcnt_t = __fsblkcnt_t;
typedef fsfilcnt_t = __fsfilcnt_t;

final class UnnamedStruct extends ffi.Struct {
  @ffi.UnsignedInt()
  external int __low;

  @ffi.UnsignedInt()
  external int __high;
}

final class __atomic_wide_counter extends ffi.Union {
  @ffi.UnsignedLongLong()
  external int __value64;

  external UnnamedStruct __value32;
}

final class __pthread_internal_list extends ffi.Struct {
  external ffi.Pointer<__pthread_internal_list> __prev;

  external ffi.Pointer<__pthread_internal_list> __next;
}

typedef __pthread_list_t = __pthread_internal_list;

final class __pthread_internal_slist extends ffi.Struct {
  external ffi.Pointer<__pthread_internal_slist> __next;
}

typedef __pthread_slist_t = __pthread_internal_slist;

final class __pthread_mutex_s extends ffi.Struct {
  @ffi.Int()
  external int __lock;

  @ffi.UnsignedInt()
  external int __count;

  @ffi.Int()
  external int __owner;

  @ffi.UnsignedInt()
  external int __nusers;

  @ffi.Int()
  external int __kind;

  @ffi.Short()
  external int __spins;

  @ffi.Short()
  external int __elision;

  external __pthread_list_t __list;
}

final class __pthread_rwlock_arch_t extends ffi.Struct {
  @ffi.UnsignedInt()
  external int __readers;

  @ffi.UnsignedInt()
  external int __writers;

  @ffi.UnsignedInt()
  external int __wrphase_futex;

  @ffi.UnsignedInt()
  external int __writers_futex;

  @ffi.UnsignedInt()
  external int __pad3;

  @ffi.UnsignedInt()
  external int __pad4;

  @ffi.Int()
  external int __cur_writer;

  @ffi.Int()
  external int __shared;

  @ffi.SignedChar()
  external int __rwelision;

  @ffi.Array.multi([7])
  external ffi.Array<ffi.UnsignedChar> __pad1;

  @ffi.UnsignedLong()
  external int __pad2;

  @ffi.UnsignedInt()
  external int __flags;
}

final class __pthread_cond_s extends ffi.Struct {
  external __atomic_wide_counter __wseq;

  external __atomic_wide_counter __g1_start;

  @ffi.Array.multi([2])
  external ffi.Array<ffi.UnsignedInt> __g_size;

  @ffi.UnsignedInt()
  external int __g1_orig_size;

  @ffi.UnsignedInt()
  external int __wrefs;

  @ffi.Array.multi([2])
  external ffi.Array<ffi.UnsignedInt> __g_signals;

  @ffi.UnsignedInt()
  external int __unused_initialized_1;

  @ffi.UnsignedInt()
  external int __unused_initialized_2;
}

typedef __tss_t = ffi.UnsignedInt;
typedef Dart__tss_t = int;
typedef __thrd_t = ffi.UnsignedLong;
typedef Dart__thrd_t = int;

final class __once_flag extends ffi.Struct {
  @ffi.Int()
  external int __data;
}

typedef pthread_t = ffi.UnsignedLong;
typedef Dartpthread_t = int;

final class pthread_mutexattr_t extends ffi.Union {
  @ffi.Array.multi([4])
  external ffi.Array<ffi.Char> __size;

  @ffi.Int()
  external int __align;
}

final class pthread_condattr_t extends ffi.Union {
  @ffi.Array.multi([4])
  external ffi.Array<ffi.Char> __size;

  @ffi.Int()
  external int __align;
}

typedef pthread_key_t = ffi.UnsignedInt;
typedef Dartpthread_key_t = int;
typedef pthread_once_t = ffi.Int;
typedef Dartpthread_once_t = int;

final class pthread_attr_t extends ffi.Union {
  @ffi.Array.multi([56])
  external ffi.Array<ffi.Char> __size;

  @ffi.Long()
  external int __align;
}

final class pthread_mutex_t extends ffi.Union {
  external __pthread_mutex_s __data;

  @ffi.Array.multi([40])
  external ffi.Array<ffi.Char> __size;

  @ffi.Long()
  external int __align;
}

final class pthread_cond_t extends ffi.Union {
  external __pthread_cond_s __data;

  @ffi.Array.multi([48])
  external ffi.Array<ffi.Char> __size;

  @ffi.LongLong()
  external int __align;
}

final class pthread_rwlock_t extends ffi.Union {
  external __pthread_rwlock_arch_t __data;

  @ffi.Array.multi([56])
  external ffi.Array<ffi.Char> __size;

  @ffi.Long()
  external int __align;
}

final class pthread_rwlockattr_t extends ffi.Union {
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Char> __size;

  @ffi.Long()
  external int __align;
}

final class pthread_barrier_t extends ffi.Union {
  @ffi.Array.multi([32])
  external ffi.Array<ffi.Char> __size;

  @ffi.Long()
  external int __align;
}

final class pthread_barrierattr_t extends ffi.Union {
  @ffi.Array.multi([4])
  external ffi.Array<ffi.Char> __size;

  @ffi.Int()
  external int __align;
}

final class random_data extends ffi.Struct {
  external ffi.Pointer<ffi.Int32> fptr;

  external ffi.Pointer<ffi.Int32> rptr;

  external ffi.Pointer<ffi.Int32> state;

  @ffi.Int()
  external int rand_type;

  @ffi.Int()
  external int rand_deg;

  @ffi.Int()
  external int rand_sep;

  external ffi.Pointer<ffi.Int32> end_ptr;
}

final class drand48_data extends ffi.Struct {
  @ffi.Array.multi([3])
  external ffi.Array<ffi.UnsignedShort> __x;

  @ffi.Array.multi([3])
  external ffi.Array<ffi.UnsignedShort> __old_x;

  @ffi.UnsignedShort()
  external int __c;

  @ffi.UnsignedShort()
  external int __init;

  @ffi.UnsignedLongLong()
  external int __a;
}

typedef __compar_fn_tFunction =
    ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>);
typedef Dart__compar_fn_tFunction =
    int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>);
typedef __compar_fn_t = ffi.Pointer<ffi.NativeFunction<__compar_fn_tFunction>>;

final class UnnamedUnion extends ffi.Union {
  @ffi.UnsignedInt()
  external int __wch;

  @ffi.Array.multi([4])
  external ffi.Array<ffi.Char> __wchb;
}

final class __mbstate_t extends ffi.Struct {
  @ffi.Int()
  external int __count;

  external UnnamedUnion __value;
}

final class _G_fpos_t extends ffi.Struct {
  @__off_t()
  external int __pos;

  external __mbstate_t __state;
}

typedef __fpos_t = _G_fpos_t;

final class _G_fpos64_t extends ffi.Struct {
  @__off64_t()
  external int __pos;

  external __mbstate_t __state;
}

typedef __fpos64_t = _G_fpos64_t;

final class _IO_FILE extends ffi.Opaque {}

typedef __FILE = _IO_FILE;
typedef FILE = _IO_FILE;

final class _IO_marker extends ffi.Opaque {}

final class _IO_codecvt extends ffi.Opaque {}

final class _IO_wide_data extends ffi.Opaque {}

typedef _IO_lock_t = ffi.Void;
typedef Dart_IO_lock_t = void;
typedef cookie_read_function_t =
    ffi.NativeFunction<
      __ssize_t Function(
        ffi.Pointer<ffi.Void> __cookie,
        ffi.Pointer<ffi.Char> __buf,
        ffi.Size __nbytes,
      )
    >;
typedef cookie_write_function_t =
    ffi.NativeFunction<
      __ssize_t Function(
        ffi.Pointer<ffi.Void> __cookie,
        ffi.Pointer<ffi.Char> __buf,
        ffi.Size __nbytes,
      )
    >;
typedef cookie_seek_function_t =
    ffi.NativeFunction<
      ffi.Int Function(
        ffi.Pointer<ffi.Void> __cookie,
        ffi.Pointer<__off64_t> __pos,
        ffi.Int __w,
      )
    >;
typedef cookie_close_function_t =
    ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Void> __cookie)>;

final class _IO_cookie_io_functions_t extends ffi.Struct {
  external ffi.Pointer<cookie_read_function_t> read;

  external ffi.Pointer<cookie_write_function_t> write;

  external ffi.Pointer<cookie_seek_function_t> seek;

  external ffi.Pointer<cookie_close_function_t> close;
}

typedef cookie_io_functions_t = _IO_cookie_io_functions_t;
typedef fpos_t = __fpos_t;

final class __va_list_tag extends ffi.Struct {
  @ffi.UnsignedInt()
  external int gp_offset;

  @ffi.UnsignedInt()
  external int fp_offset;

  external ffi.Pointer<ffi.Void> overflow_arg_area;

  external ffi.Pointer<ffi.Void> reg_save_area;
}

typedef float_t = ffi.Float;
typedef Dartfloat_t = double;
typedef double_t = ffi.Double;
typedef Dartdouble_t = double;

final class __locale_data extends ffi.Opaque {}

final class __locale_struct extends ffi.Struct {
  @ffi.Array.multi([13])
  external ffi.Array<ffi.Pointer<__locale_data>> __locales;

  external ffi.Pointer<ffi.UnsignedShort> __ctype_b;

  external ffi.Pointer<ffi.Int> __ctype_tolower;

  external ffi.Pointer<ffi.Int> __ctype_toupper;

  @ffi.Array.multi([13])
  external ffi.Array<ffi.Pointer<ffi.Char>> __names;
}

typedef __locale_t = ffi.Pointer<__locale_struct>;
typedef locale_t = __locale_t;

final class kiss_fft_cpx extends ffi.Struct {
  @ffi.Double()
  external double r;

  @ffi.Double()
  external double i;
}

final class kiss_fft_state extends ffi.Opaque {}

typedef kiss_fft_cfg = ffi.Pointer<kiss_fft_state>;

final class kiss_fftr_state extends ffi.Opaque {}

/// Real optimized version can save about 45% cpu time vs. complex fft of a real seq.
typedef kiss_fftr_cfg = ffi.Pointer<kiss_fftr_state>;

const int FP_NAN$1 = 0;

const int FP_INFINITE$1 = 1;

const int FP_ZERO$1 = 2;

const int FP_SUBNORMAL$1 = 3;

const int FP_NORMAL$1 = 4;

const int _FEATURES_H = 1;

const int _DEFAULT_SOURCE = 1;

const int __GLIBC_USE_ISOC2Y = 1;

const int __GLIBC_USE_ISOC23 = 1;

const int __USE_ISOC11 = 1;

const int __USE_ISOC99 = 1;

const int __USE_ISOC95 = 1;

const int _POSIX_SOURCE = 1;

const int _POSIX_C_SOURCE = 200809;

const int __USE_POSIX = 1;

const int __USE_POSIX2 = 1;

const int __USE_POSIX199309 = 1;

const int __USE_POSIX199506 = 1;

const int __USE_XOPEN2K = 1;

const int __USE_XOPEN2K8 = 1;

const int _ATFILE_SOURCE = 1;

const int __WORDSIZE = 64;

const int __WORDSIZE_TIME64_COMPAT32 = 1;

const int __SYSCALL_WORDSIZE = 64;

const int __TIMESIZE = 64;

const int __USE_TIME_BITS64 = 1;

const int __USE_MISC = 1;

const int __USE_ATFILE = 1;

const int __USE_FORTIFY_LEVEL = 0;

const int __GLIBC_USE_DEPRECATED_GETS = 0;

const int __GLIBC_USE_DEPRECATED_SCANF = 0;

const int __GLIBC_USE_C23_STRTOL = 1;

const int _STDC_PREDEF_H = 1;

const int __STDC_IEC_559__ = 1;

const int __STDC_IEC_60559_BFP__ = 201404;

const int __STDC_IEC_559_COMPLEX__ = 1;

const int __STDC_IEC_60559_COMPLEX__ = 201404;

const int __STDC_ISO_10646__ = 201706;

const int __GNU_LIBRARY__ = 6;

const int __GLIBC__ = 2;

const int __GLIBC_MINOR__ = 42;

const int _SYS_CDEFS_H = 1;

const int __THROW = 1;

const int __THROWNL = 1;

const int __glibc_c99_flexarr_available = 1;

const int __LDOUBLE_REDIRECTS_TO_FLOAT128_ABI = 0;

const int __HAVE_GENERIC_SELECTION = 0;

const int __GLIBC_USE_LIB_EXT2 = 1;

const int __GLIBC_USE_IEC_60559_BFP_EXT = 1;

const int __GLIBC_USE_IEC_60559_BFP_EXT_C23 = 1;

const int __GLIBC_USE_IEC_60559_EXT = 1;

const int __GLIBC_USE_IEC_60559_FUNCS_EXT = 1;

const int __GLIBC_USE_IEC_60559_FUNCS_EXT_C23 = 1;

const int __GLIBC_USE_IEC_60559_TYPES_EXT = 1;

const int NULL = 0;

const int _STDLIB_H = 1;

const int WNOHANG = 1;

const int WUNTRACED = 2;

const int WSTOPPED = 2;

const int WEXITED = 4;

const int WCONTINUED = 8;

const int WNOWAIT = 16777216;

const int __WNOTHREAD = 536870912;

const int __WALL = 1073741824;

const int __WCLONE = 2147483648;

const int __W_CONTINUED = 65535;

const int __WCOREFLAG = 128;

const int __HAVE_FLOAT128 = 1;

const int __HAVE_DISTINCT_FLOAT128 = 1;

const int __HAVE_FLOAT64X = 1;

const int __HAVE_FLOAT64X_LONG_DOUBLE = 1;

const int __HAVE_FLOAT16 = 0;

const int __HAVE_FLOAT32 = 1;

const int __HAVE_FLOAT64 = 1;

const int __HAVE_FLOAT32X = 1;

const int __HAVE_FLOAT128X = 0;

const int __HAVE_DISTINCT_FLOAT16 = 0;

const int __HAVE_DISTINCT_FLOAT32 = 0;

const int __HAVE_DISTINCT_FLOAT64 = 0;

const int __HAVE_DISTINCT_FLOAT32X = 0;

const int __HAVE_DISTINCT_FLOAT64X = 0;

const int __HAVE_DISTINCT_FLOAT128X = 0;

const int __HAVE_FLOAT128_UNLIKE_LDBL = 1;

const int __HAVE_FLOATN_NOT_TYPEDEF = 0;

const int __ldiv_t_defined = 1;

const int __lldiv_t_defined = 1;

const int RAND_MAX = 2147483647;

const int EXIT_FAILURE = 1;

const int EXIT_SUCCESS = 0;

const int _SYS_TYPES_H = 1;

const int _BITS_TYPES_H = 1;

const int _BITS_TYPESIZES_H = 1;

const int __OFF_T_MATCHES_OFF64_T = 1;

const int __INO_T_MATCHES_INO64_T = 1;

const int __RLIM_T_MATCHES_RLIM64_T = 1;

const int __STATFS_MATCHES_STATFS64 = 1;

const int __KERNEL_OLD_TIMEVAL_MATCHES_TIMEVAL64 = 1;

const int __FD_SETSIZE = 1024;

const int _BITS_TIME64_H = 1;

const int __clock_t_defined = 1;

const int __clockid_t_defined = 1;

const int __time_t_defined = 1;

const int __timer_t_defined = 1;

const int _BITS_STDINT_INTN_H = 1;

const int __BIT_TYPES_DEFINED__ = 1;

const int _ENDIAN_H = 1;

const int _BITS_ENDIAN_H = 1;

const int __LITTLE_ENDIAN = 1234;

const int __BIG_ENDIAN = 4321;

const int __PDP_ENDIAN = 3412;

const int _BITS_ENDIANNESS_H = 1;

const int __BYTE_ORDER = 1234;

const int __FLOAT_WORD_ORDER = 1234;

const int LITTLE_ENDIAN = 1234;

const int BIG_ENDIAN = 4321;

const int PDP_ENDIAN = 3412;

const int BYTE_ORDER = 1234;

const int _BITS_BYTESWAP_H = 1;

const int _BITS_UINTN_IDENTITY_H = 1;

const int _SYS_SELECT_H = 1;

const int __sigset_t_defined = 1;

const int _SIGSET_NWORDS = 16;

const int __timeval_defined = 1;

const int _STRUCT_TIMESPEC = 1;

const int __NFDBITS = 64;

const int FD_SETSIZE = 1024;

const int NFDBITS = 64;

const int _BITS_PTHREADTYPES_COMMON_H = 1;

const int _THREAD_SHARED_TYPES_H = 1;

const int _BITS_PTHREADTYPES_ARCH_H = 1;

const int __SIZEOF_PTHREAD_MUTEX_T = 40;

const int __SIZEOF_PTHREAD_ATTR_T = 56;

const int __SIZEOF_PTHREAD_RWLOCK_T = 56;

const int __SIZEOF_PTHREAD_BARRIER_T = 32;

const int __SIZEOF_PTHREAD_MUTEXATTR_T = 4;

const int __SIZEOF_PTHREAD_COND_T = 48;

const int __SIZEOF_PTHREAD_CONDATTR_T = 4;

const int __SIZEOF_PTHREAD_RWLOCKATTR_T = 8;

const int __SIZEOF_PTHREAD_BARRIERATTR_T = 4;

const int _THREAD_MUTEX_INTERNAL_H = 1;

const int __PTHREAD_MUTEX_HAVE_PREV = 1;

const int __PTHREAD_RWLOCK_ELISION_EXTRA = 0;

const int __have_pthread_attr_t = 1;

const int _ALLOCA_H = 1;

const int _STDIO_H = 1;

const int _____fpos_t_defined = 1;

const int ____mbstate_t_defined = 1;

const int _____fpos64_t_defined = 1;

const int ____FILE_defined = 1;

const int __FILE_defined = 1;

const int __struct_FILE_defined = 1;

const int _IO_EOF_SEEN = 16;

const int _IO_ERR_SEEN = 32;

const int _IO_USER_LOCK = 32768;

const int __cookie_io_functions_t_defined = 1;

const int _IOFBF = 0;

const int _IOLBF = 1;

const int _IONBF = 2;

const int BUFSIZ = 8192;

const int EOF = -1;

const int SEEK_SET = 0;

const int SEEK_CUR = 1;

const int SEEK_END = 2;

const String P_tmpdir = '/tmp';

const int L_tmpnam = 20;

const int TMP_MAX = 238328;

const int _BITS_STDIO_LIM_H = 1;

const int FILENAME_MAX = 4096;

const int L_ctermid = 9;

const int FOPEN_MAX = 16;

const int _MATH_H = 1;

const int _BITS_LIBM_SIMD_DECL_STUBS_H = 1;

const double HUGE_VAL = double.infinity;

const double HUGE_VALF = double.infinity;

const double HUGE_VALL = double.infinity;

const double INFINITY = double.infinity;

const double NAN = double.nan;

const int __GLIBC_FLT_EVAL_METHOD = 0;

const int __FP_LOGB0_IS_MIN = 1;

const int __FP_LOGBNAN_IS_MIN = 1;

const int FP_ILOGB0 = -2147483648;

const int FP_ILOGBNAN = -2147483648;

const int __MATH_DECLARE_LDOUBLE = 1;

const int FP_NAN = 0;

const int FP_INFINITE = 1;

const int FP_ZERO = 2;

const int FP_SUBNORMAL = 3;

const int FP_NORMAL = 4;

const int MATH_ERRNO = 1;

const int MATH_ERREXCEPT = 2;

const int math_errhandling = 3;

const double M_E = 2.718281828459045;

const double M_LOG2E = 1.4426950408889634;

const double M_LOG10E = 0.4342944819032518;

const double M_LN2 = 0.6931471805599453;

const double M_LN10 = 2.302585092994046;

const double M_PI = 3.141592653589793;

const double M_PI_2 = 1.5707963267948966;

const double M_PI_4 = 0.7853981633974483;

const double M_1_PI = 0.3183098861837907;

const double M_2_PI = 0.6366197723675814;

const double M_2_SQRTPI = 1.1283791670955126;

const double M_SQRT2 = 1.4142135623730951;

const double M_SQRT1_2 = 0.7071067811865476;

const int _STRING_H = 1;

const int _BITS_TYPES_LOCALE_T_H = 1;

const int _BITS_TYPES___LOCALE_T_H = 1;

const int _STRINGS_H = 1;
