// Copyright (c) 2026, Sigurd Meldgaard. All rights reserved.
//
// Downloads precompiled binary artifacts for a GitHub Release (or reads them
// from a local directory), verifies their SLSA v1.0 build provenance via
// `gh attestation verify`, computes SHA-256 digests, and updates
// `pkgs/<pkg>/lib/src/hook_helpers/hashes.dart`.

import 'dart:io';
import 'dart:typed_data';

import 'package:args/args.dart';
import 'package:code_assets/code_assets.dart';
import 'package:crypto/crypto.dart';

const _supportedTargets = <(OS, Architecture)>[
  (OS.linux, Architecture.x64),
  (OS.linux, Architecture.arm64),
  (OS.macOS, Architecture.arm64),
  (OS.macOS, Architecture.x64),
  (OS.windows, Architecture.x64),
];

Future<void> main(List<String> args) async {
  final parser = ArgParser()
    ..addOption(
      'repo',
      abbr: 'r',
      defaultsTo: 'sigurdm/scientific_dart',
      help:
          'GitHub repository (<owner>/<name>) hosting releases and attestations.',
    )
    ..addOption(
      'local-dir',
      abbr: 'l',
      help:
          'Optional local directory containing built artifacts (instead of downloading from GitHub).',
    )
    ..addFlag(
      'skip-provenance',
      negatable: false,
      help:
          'Skip `gh attestation verify` check (only use for local dry runs before release).',
    )
    ..addFlag(
      'help',
      abbr: 'h',
      negatable: false,
      help: 'Show usage information.',
    );

  final ArgResults parsed;
  try {
    parsed = parser.parse(args);
  } catch (e) {
    stderr.writeln('Error: $e\n\n${parser.usage}');
    exit(64);
  }

  if (parsed.flag('help') || parsed.rest.isEmpty) {
    stdout.writeln(
      'Usage: dart tool/regenerate_hashes.dart <release-tag> [options]\n',
    );
    stdout.writeln(parser.usage);
    exit(parsed.flag('help') ? 0 : 64);
  }

  final version = parsed.rest.first;
  final repo = parsed.option('repo')!;
  final localDirOption = parsed.option('local-dir');
  final skipProvenance = parsed.flag('skip-provenance');
  final localDir = localDirOption != null ? Directory(localDirOption) : null;

  final tempDir = await Directory.systemTemp.createTemp(
    'scientific_dart_hashes_',
  );
  try {
    // 1. Update pocketfft hashes
    await _regenerateSingleAssetHashes(
      packageName: 'pocketfft',
      assetStem: 'pocketfft',
      helperFuncName: 'pocketfftArtifactName',
      version: version,
      repo: repo,
      localDir: localDir,
      tempDir: tempDir,
      skipProvenance: skipProvenance,
    );

    // 2. Update ndarray hashes
    await _regenerateSingleAssetHashes(
      packageName: 'ndarray',
      assetStem: 'ndarray',
      helperFuncName: 'ndarrayArtifactName',
      version: version,
      repo: repo,
      localDir: localDir,
      tempDir: tempDir,
      skipProvenance: skipProvenance,
    );

    // 3. Update openblas hashes (openblas + openblas_extensions)
    await _regenerateMultiAssetHashes(
      packageName: 'openblas',
      assetStems: const ['openblas', 'openblas_extensions'],
      helperFuncName: 'openblasArtifactName',
      version: version,
      repo: repo,
      localDir: localDir,
      tempDir: tempDir,
      skipProvenance: skipProvenance,
    );
  } finally {
    try {
      await tempDir.delete(recursive: true);
    } catch (_) {}
  }
}

Future<void> _regenerateSingleAssetHashes({
  required String packageName,
  required String assetStem,
  required String helperFuncName,
  required String version,
  required String repo,
  required Directory? localDir,
  required Directory tempDir,
  required bool skipProvenance,
}) async {
  stdout.writeln('=== Updating hashes for package:$packageName ($version) ===');
  final hashes = <(OS, Architecture), String>{};

  for (final (os, arch) in _supportedTargets) {
    final ext = _extForOS(os);
    final artifactName = '$assetStem-${os.name}-${arch.name}.$ext';
    final file = await _obtainArtifact(
      artifactName: artifactName,
      version: version,
      repo: repo,
      localDir: localDir,
      tempDir: tempDir,
    );

    if (file == null) {
      stdout.writeln('  [skip] $artifactName not found');
      hashes[(os, arch)] = '0' * 64;
      continue;
    }

    if (!skipProvenance) {
      await _verifyProvenance(file: file, repo: repo);
    }

    final digest = sha256.convert(await file.readAsBytes()).toString();
    hashes[(os, arch)] = digest;
    stdout.writeln('  [ok]   $artifactName -> $digest');
  }

  final entriesCode = hashes.entries
      .map(
        (e) =>
            '  (${_osConstName(e.key.$1)}, Architecture.${e.key.$2.name}):\n'
            "      '${e.value}',",
      )
      .join('\n');

  final targetFile = File('pkgs/$packageName/lib/src/hook_helpers/hashes.dart');
  await targetFile.writeAsString('''
// THIS FILE IS AUTOGENERATED BY `tool/regenerate_hashes.dart`. TO UPDATE, RUN:
//
//   dart tool/regenerate_hashes.dart <github release tag>
//

import 'package:code_assets/code_assets.dart';

/// GitHub repository hosting prebuilt release artifacts and SLSA provenance attestations.
const repository = '$repo';

/// Release tag for prebuilt `$packageName` binaries.
const version = '$version';

/// Canonical release artifact filename for `(os, arch)`.
String $helperFuncName(OS os, Architecture arch) {
  final ext = switch (os) {
    OS.windows => 'dll',
    OS.macOS || OS.iOS => 'dylib',
    _ => 'so',
  };
  return '$assetStem-\${os.name}-\${arch.name}.\$ext';
}

/// SHA-256 digests for prebuilt `$packageName` binaries indexed by `(OS, Architecture)`.
const fileHashes = <(OS, Architecture), String>{
$entriesCode
};
''');
  stdout.writeln('Wrote ${targetFile.path}');
}

Future<void> _regenerateMultiAssetHashes({
  required String packageName,
  required List<String> assetStems,
  required String helperFuncName,
  required String version,
  required String repo,
  required Directory? localDir,
  required Directory tempDir,
  required bool skipProvenance,
}) async {
  stdout.writeln('=== Updating hashes for package:$packageName ($version) ===');
  final hashes = <(OS, Architecture, String), String>{};

  for (final (os, arch) in _supportedTargets) {
    final ext = _extForOS(os);
    for (final stem in assetStems) {
      final artifactName = '$stem-${os.name}-${arch.name}.$ext';
      final file = await _obtainArtifact(
        artifactName: artifactName,
        version: version,
        repo: repo,
        localDir: localDir,
        tempDir: tempDir,
      );

      if (file == null) {
        stdout.writeln('  [skip] $artifactName not found');
        hashes[(os, arch, stem)] = '0' * 64;
        continue;
      }

      if (!skipProvenance) {
        await _verifyProvenance(file: file, repo: repo);
      }

      final digest = sha256.convert(await file.readAsBytes()).toString();
      hashes[(os, arch, stem)] = digest;
      stdout.writeln('  [ok]   $artifactName -> $digest');
    }
  }

  final entriesCode = hashes.entries
      .map(
        (e) =>
            "  (${_osConstName(e.key.$1)}, Architecture.${e.key.$2.name}, '${e.key.$3}'):\n"
            "      '${e.value}',",
      )
      .join('\n');

  final targetFile = File('pkgs/$packageName/lib/src/hook_helpers/hashes.dart');
  await targetFile.writeAsString('''
// THIS FILE IS AUTOGENERATED BY `tool/regenerate_hashes.dart`. TO UPDATE, RUN:
//
//   dart tool/regenerate_hashes.dart <github release tag>
//

import 'package:code_assets/code_assets.dart';

/// GitHub repository hosting prebuilt release artifacts and SLSA provenance attestations.
const repository = '$repo';

/// Release tag for prebuilt `$packageName` binaries.
const version = '$version';

/// Canonical release artifact filename for `(os, arch, libraryKind)`.
///
/// [libraryKind] is either `'openblas'` or `'openblas_extensions'`.
String $helperFuncName(OS os, Architecture arch, String libraryKind) {
  final ext = switch (os) {
    OS.windows => 'dll',
    OS.macOS || OS.iOS => 'dylib',
    _ => 'so',
  };
  return '\$libraryKind-\${os.name}-\${arch.name}.\$ext';
}

/// SHA-256 digests for prebuilt `$packageName` binaries indexed by `(OS, Architecture, libraryKind)`.
const fileHashes = <(OS, Architecture, String), String>{
$entriesCode
};
''');
  stdout.writeln('Wrote ${targetFile.path}');
}

String _osConstName(OS os) => switch (os) {
  OS.macOS => 'OS.macOS',
  OS.iOS => 'OS.iOS',
  _ => 'OS.${os.name}',
};

String _extForOS(OS os) => switch (os) {
  OS.windows => 'dll',
  OS.macOS || OS.iOS => 'dylib',
  _ => 'so',
};

Future<File?> _obtainArtifact({
  required String artifactName,
  required String version,
  required String repo,
  required Directory? localDir,
  required Directory tempDir,
}) async {
  if (localDir != null) {
    final candidate = File.fromUri(localDir.uri.resolve(artifactName));
    return candidate.existsSync() ? candidate : null;
  }

  final uri = Uri.parse(
    'https://github.com/$repo/releases/download/$version/$artifactName',
  );
  final bytes = await _downloadWithRedirects(uri);
  if (bytes == null) return null;

  final dst = File.fromUri(tempDir.uri.resolve(artifactName));
  await dst.writeAsBytes(bytes, flush: true);
  return dst;
}

Future<void> _verifyProvenance({
  required File file,
  required String repo,
}) async {
  stdout.writeln(
    '  [provenance] Verifying SLSA attestation for ${file.uri.pathSegments.last}...',
  );
  final res = await Process.run('gh', [
    'attestation',
    'verify',
    file.path,
    '--repo',
    repo,
  ]);
  if (res.exitCode != 0) {
    throw StateError(
      'SLSA provenance verification failed for ${file.path} against $repo:\n'
      'stdout: ${res.stdout}\n'
      'stderr: ${res.stderr}',
    );
  }
}

Future<Uint8List?> _downloadWithRedirects(Uri url) async {
  final client = HttpClient();
  try {
    var currentUrl = url;
    for (var redirectCount = 0; redirectCount < 5; redirectCount++) {
      final request = await client.getUrl(currentUrl);
      final response = await request.close();
      if (response.statusCode >= 300 &&
          response.statusCode < 400 &&
          response.headers.value(HttpHeaders.locationHeader) != null) {
        currentUrl = currentUrl.resolve(
          response.headers.value(HttpHeaders.locationHeader)!,
        );
        continue;
      }
      if (response.statusCode == 404) {
        return null;
      }
      if (response.statusCode != 200) {
        throw HttpException(
          'Failed to download $currentUrl (HTTP ${response.statusCode})',
        );
      }
      final builder = BytesBuilder(copy: false);
      await for (final chunk in response) {
        builder.add(chunk);
      }
      return builder.takeBytes();
    }
    throw HttpException('Too many redirects while downloading $url');
  } finally {
    client.close();
  }
}
