// THIS FILE IS AUTOGENERATED BY `tool/regenerate_hashes.dart`. TO UPDATE, RUN:
//
//   dart tool/regenerate_hashes.dart <github release tag>
//

import 'package:code_assets/code_assets.dart';

/// GitHub repository hosting prebuilt release artifacts and SLSA provenance attestations.
const repository = 'sigurdm/scientific_dart';

/// Release tag for prebuilt `symbolic_dart` binaries.
const version = 'artifacts-v0.0.2';

/// Canonical release artifact filename for `(os, arch, libraryKind)`.
///
/// [libraryKind] is either `'flint'` or `'symengine'`.
String symbolicDartArtifactName(OS os, Architecture arch, String libraryKind) {
  final ext = switch (os) {
    OS.windows => 'dll',
    OS.macOS || OS.iOS => 'dylib',
    _ => 'so',
  };
  return '$libraryKind-${os.name}-${arch.name}.$ext';
}

/// SHA-256 digests for prebuilt `symbolic_dart` binaries indexed by `(OS, Architecture, libraryKind)`.
const fileHashes = <(OS, Architecture, String), String>{
  (OS.linux, Architecture.x64, 'flint'):
      '0000000000000000000000000000000000000000000000000000000000000000',
  (OS.linux, Architecture.x64, 'symengine'):
      '0000000000000000000000000000000000000000000000000000000000000000',
  (OS.linux, Architecture.arm64, 'flint'):
      '0000000000000000000000000000000000000000000000000000000000000000',
  (OS.linux, Architecture.arm64, 'symengine'):
      '0000000000000000000000000000000000000000000000000000000000000000',
  (OS.macOS, Architecture.arm64, 'flint'):
      '0000000000000000000000000000000000000000000000000000000000000000',
  (OS.macOS, Architecture.arm64, 'symengine'):
      '0000000000000000000000000000000000000000000000000000000000000000',
  (OS.macOS, Architecture.x64, 'flint'):
      '0000000000000000000000000000000000000000000000000000000000000000',
  (OS.macOS, Architecture.x64, 'symengine'):
      '0000000000000000000000000000000000000000000000000000000000000000',
  (OS.windows, Architecture.x64, 'flint'):
      '0000000000000000000000000000000000000000000000000000000000000000',
  (OS.windows, Architecture.x64, 'symengine'):
      '0000000000000000000000000000000000000000000000000000000000000000',
};
