// THIS FILE IS AUTOGENERATED BY `tool/regenerate_hashes.dart`. TO UPDATE, RUN:
//
//   dart tool/regenerate_hashes.dart <github release tag>
//

import 'package:code_assets/code_assets.dart';

/// GitHub repository hosting prebuilt release artifacts and SLSA provenance attestations.
const repository = 'sigurdm/scientific_dart';

/// Release tag for prebuilt `openblas` binaries.
const version = 'artifacts-v0.0.2';

/// Canonical release artifact filename for `(os, arch, libraryKind)`.
///
/// [libraryKind] is either `'openblas'` or `'openblas_extensions'`.
String openblasArtifactName(OS os, Architecture arch, String libraryKind) {
  final ext = switch (os) {
    OS.windows => 'dll',
    OS.macOS || OS.iOS => 'dylib',
    _ => 'so',
  };
  return '$libraryKind-${os.name}-${arch.name}.$ext';
}

/// SHA-256 digests for prebuilt `openblas` binaries indexed by `(OS, Architecture, libraryKind)`.
const fileHashes = <(OS, Architecture, String), String>{
  (OS.linux, Architecture.x64, 'openblas'):
      'cbb8821be5909cdb5ff614f088da5648adb0cde33bb335e6c9017c93b63a626b',
  (OS.linux, Architecture.x64, 'openblas_extensions'):
      '86a826ebdb3a76904cfe465189fb5b592127660acaec757b671cc620a083ace9',
  (OS.linux, Architecture.arm64, 'openblas'):
      '0000000000000000000000000000000000000000000000000000000000000000',
  (OS.linux, Architecture.arm64, 'openblas_extensions'):
      '0000000000000000000000000000000000000000000000000000000000000000',
  (OS.macOS, Architecture.arm64, 'openblas'):
      '0000000000000000000000000000000000000000000000000000000000000000',
  (OS.macOS, Architecture.arm64, 'openblas_extensions'):
      '0000000000000000000000000000000000000000000000000000000000000000',
  (OS.macOS, Architecture.x64, 'openblas'):
      '0000000000000000000000000000000000000000000000000000000000000000',
  (OS.macOS, Architecture.x64, 'openblas_extensions'):
      '0000000000000000000000000000000000000000000000000000000000000000',
  (OS.windows, Architecture.x64, 'openblas'):
      '0000000000000000000000000000000000000000000000000000000000000000',
  (OS.windows, Architecture.x64, 'openblas_extensions'):
      '0000000000000000000000000000000000000000000000000000000000000000',
};
