// THIS FILE IS AUTOGENERATED BY `tool/regenerate_hashes.dart`. TO UPDATE, RUN:
//
//   dart tool/regenerate_hashes.dart <github release tag>
//

import 'dart:convert';
import 'dart:io';

import 'package:code_assets/code_assets.dart';
import 'package:crypto/crypto.dart';

/// GitHub repository hosting prebuilt release artifacts and SLSA provenance attestations.
const repository = 'sigurdm/scientific_dart';

/// Release tag for prebuilt `openblas` binaries.
const version = 'artifacts-v0.0.2';

/// Combined SHA-256 digest of `hook/` native source files at [version].
const nativeSourceHash =
    '5957d870c3eca66512a56f7f04eed0ef76c033a38c003d317208b5f4afb93e40';

/// Lists the tracked native source files in `hook/` under [packageRoot].
List<File> nativeSourceFiles(Uri packageRoot) {
  final hookDir = Directory.fromUri(packageRoot.resolve('hook/'));
  if (!hookDir.existsSync()) return const [];
  final files = hookDir.listSync().whereType<File>().where((file) {
    final name = file.uri.pathSegments.last;
    return name.endsWith('.dart') ||
        name.endsWith('.c') ||
        name.endsWith('.cpp') ||
        name.endsWith('.h') ||
        name.endsWith('.def');
  }).toList();
  files.sort(
    (a, b) => a.uri.pathSegments.last.compareTo(b.uri.pathSegments.last),
  );
  return files;
}

/// Computes the combined SHA-256 digest of `hook/` native source files under [packageRoot].
String computeNativeSourceHash(Uri packageRoot) {
  final buffer = StringBuffer();
  for (final file in nativeSourceFiles(packageRoot)) {
    final name = file.uri.pathSegments.last;
    final normalized = file.readAsStringSync().replaceAll('\r\n', '\n');
    final fileDigest = sha256.convert(utf8.encode(normalized)).toString();
    buffer.writeln('$name:$fileDigest');
  }
  return sha256.convert(utf8.encode(buffer.toString())).toString();
}

/// Canonical release artifact filename for `(os, arch, libraryKind)`.
///
/// [libraryKind] is either `'openblas'` or `'openblas_extensions'`.
String openblasArtifactName(OS os, Architecture arch, String libraryKind) {
  final ext = switch (os) {
    OS.windows => 'dll',
    OS.macOS || OS.iOS => 'dylib',
    _ => 'so',
  };
  return '$libraryKind-${os.name}-${arch.name}.$ext';
}

/// SHA-256 digests for prebuilt `openblas` binaries indexed by `(OS, Architecture, libraryKind)`.
const fileHashes = <(OS, Architecture, String), String>{
  (OS.linux, Architecture.x64, 'openblas'):
      '89a5bd9a56f29babae59c73f1d37cd961036664ba0b9d7fa55b1dcc29321d535',
  (OS.linux, Architecture.x64, 'openblas_extensions'):
      '0f56da9a6a34501b1bfe4f68c7028226bd2077c7d9ab0af8b5cca054b04c9a94',
  (OS.linux, Architecture.arm64, 'openblas'):
      'df645117ecf5aadc53aa2d99a6fc72b7fff1bb7efbb3af4c91e8d743c1b3fb06',
  (OS.linux, Architecture.arm64, 'openblas_extensions'):
      '6c9e8411912d2e19299bdb23923c4ed06df7c761b667dd98352aae5aaef85a5a',
  (OS.macOS, Architecture.arm64, 'openblas'):
      '94d92086467a78b1dd92615d03c958b5aefc574ea54809ab28fd7f2deffb87a7',
  (OS.macOS, Architecture.arm64, 'openblas_extensions'):
      '1d8b909bccb3a3d76981c0a66160db997de83a6ea75949f7afe93f2dbc9db0b5',
  (OS.macOS, Architecture.x64, 'openblas'):
      'c06bf9f9c7068840da139a207e9750ab800cb521687c60787e00b511a9af0e65',
  (OS.macOS, Architecture.x64, 'openblas_extensions'):
      '070412ce43b906afd6a139e153619b2f133b12d0b203ce9680422dbbe03175cd',
  (OS.windows, Architecture.x64, 'openblas'):
      'c8b6f93012b81eb5775955006a1a363d720ba2013b5262052944763e0a736346',
  (OS.windows, Architecture.x64, 'openblas_extensions'):
      'cdf4c25f95f2ca28e2218da209524ff82dff145bbdab24ce5cf9921045d5b705',
};
