name: symbolic_dart
description: Symbolic mathematics library for Dart with high-performance native CAS bindings (SymEngine & FLINT).
version: 0.0.1
resolution: workspace
repository: https://github.com/sigurdm/math

environment:
  sdk: ^3.11.5

dependencies:
  ffi: ^2.2.0
  hooks: ^1.0.3
  code_assets: ^1.0.0
  archive: ^3.6.1
  meta: ^1.18.2
  ndarray: ^0.0.2
  resource_scope: ^0.0.1

dev_dependencies:
  lints: ^6.1.0
  test: ^1.31.1
  criterion:
    git: https://github.com/sigurdm/criterion.git
  ffigen: ^20.1.1
