// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
@ffi.DefaultAsset('package:openblas/openblas')
library;

import 'dart:ffi' as ffi;

@ffi.Native<ffi.Int Function()>()
external int openblas_get_num_threads();

@ffi.Native<ffi.Pointer<ffi.Char> Function()>()
external ffi.Pointer<ffi.Char> openblas_get_config();

@ffi.Native<ffi.Void Function(ffi.Int)>()
external void openblas_set_num_threads(int num_threads);

@ffi.Native<
  ffi.Float Function(
    blasint,
    ffi.Pointer<ffi.Float>,
    blasint,
    ffi.Pointer<ffi.Float>,
    blasint,
  )
>()
external double cblas_sdot(
  int n,
  ffi.Pointer<ffi.Float> x,
  int incx,
  ffi.Pointer<ffi.Float> y,
  int incy,
);

@ffi.Native<
  ffi.Double Function(
    blasint,
    ffi.Pointer<ffi.Double>,
    blasint,
    ffi.Pointer<ffi.Double>,
    blasint,
  )
>()
external double cblas_ddot(
  int n,
  ffi.Pointer<ffi.Double> x,
  int incx,
  ffi.Pointer<ffi.Double> y,
  int incy,
);

@ffi.Native<
  ffi.Void Function(
    blasint,
    ffi.Float,
    ffi.Pointer<ffi.Float>,
    blasint,
    ffi.Pointer<ffi.Float>,
    blasint,
  )
>()
external void cblas_saxpy(
  int n,
  double alpha,
  ffi.Pointer<ffi.Float> x,
  int incx,
  ffi.Pointer<ffi.Float> y,
  int incy,
);

@ffi.Native<
  ffi.Void Function(
    blasint,
    ffi.Double,
    ffi.Pointer<ffi.Double>,
    blasint,
    ffi.Pointer<ffi.Double>,
    blasint,
  )
>()
external void cblas_daxpy(
  int n,
  double alpha,
  ffi.Pointer<ffi.Double> x,
  int incx,
  ffi.Pointer<ffi.Double> y,
  int incy,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Int,
    ffi.Int,
    ffi.Int,
    blasint,
    blasint,
    blasint,
    ffi.Double,
    ffi.Pointer<ffi.Double>,
    blasint,
    ffi.Pointer<ffi.Double>,
    blasint,
    ffi.Double,
    ffi.Pointer<ffi.Double>,
    blasint,
  )
>()
external void cblas_dgemm(
  int order,
  int transA,
  int transB,
  int m,
  int n,
  int k,
  double alpha,
  ffi.Pointer<ffi.Double> a,
  int lda,
  ffi.Pointer<ffi.Double> b,
  int ldb,
  double beta,
  ffi.Pointer<ffi.Double> c,
  int ldc,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Int,
    ffi.Int,
    ffi.Int,
    blasint,
    blasint,
    blasint,
    ffi.Float,
    ffi.Pointer<ffi.Float>,
    blasint,
    ffi.Pointer<ffi.Float>,
    blasint,
    ffi.Float,
    ffi.Pointer<ffi.Float>,
    blasint,
  )
>()
external void cblas_sgemm(
  int order,
  int transA,
  int transB,
  int m,
  int n,
  int k,
  double alpha,
  ffi.Pointer<ffi.Float> a,
  int lda,
  ffi.Pointer<ffi.Float> b,
  int ldb,
  double beta,
  ffi.Pointer<ffi.Float> c,
  int ldc,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    lapack_int,
    lapack_int,
    ffi.Pointer<ffi.Double>,
    lapack_int,
    ffi.Pointer<lapack_int>,
  )
>()
external int LAPACKE_dgetrf(
  int matrix_layout,
  int m,
  int n,
  ffi.Pointer<ffi.Double> a,
  int lda,
  ffi.Pointer<lapack_int> ipiv,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    lapack_int,
    ffi.Pointer<ffi.Double>,
    lapack_int,
    ffi.Pointer<lapack_int>,
  )
>()
external int LAPACKE_dgetri(
  int matrix_layout,
  int n,
  ffi.Pointer<ffi.Double> a,
  int lda,
  ffi.Pointer<lapack_int> ipiv,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    lapack_int,
    lapack_int,
    ffi.Pointer<ffi.Float>,
    lapack_int,
    ffi.Pointer<lapack_int>,
  )
>()
external int LAPACKE_sgetrf(
  int matrix_layout,
  int m,
  int n,
  ffi.Pointer<ffi.Float> a,
  int lda,
  ffi.Pointer<lapack_int> ipiv,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    lapack_int,
    ffi.Pointer<ffi.Float>,
    lapack_int,
    ffi.Pointer<lapack_int>,
  )
>()
external int LAPACKE_sgetri(
  int matrix_layout,
  int n,
  ffi.Pointer<ffi.Float> a,
  int lda,
  ffi.Pointer<lapack_int> ipiv,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    lapack_int,
    lapack_int,
    ffi.Pointer<ffi.Float>,
    lapack_int,
    ffi.Pointer<lapack_int>,
  )
>()
external int LAPACKE_cgetrf(
  int matrix_layout,
  int m,
  int n,
  ffi.Pointer<ffi.Float> a,
  int lda,
  ffi.Pointer<lapack_int> ipiv,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    lapack_int,
    ffi.Pointer<ffi.Float>,
    lapack_int,
    ffi.Pointer<lapack_int>,
  )
>()
external int LAPACKE_cgetri(
  int matrix_layout,
  int n,
  ffi.Pointer<ffi.Float> a,
  int lda,
  ffi.Pointer<lapack_int> ipiv,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    lapack_int,
    lapack_int,
    ffi.Pointer<ffi.Double>,
    lapack_int,
    ffi.Pointer<lapack_int>,
  )
>()
external int LAPACKE_zgetrf(
  int matrix_layout,
  int m,
  int n,
  ffi.Pointer<ffi.Double> a,
  int lda,
  ffi.Pointer<lapack_int> ipiv,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    lapack_int,
    ffi.Pointer<ffi.Double>,
    lapack_int,
    ffi.Pointer<lapack_int>,
  )
>()
external int LAPACKE_zgetri(
  int matrix_layout,
  int n,
  ffi.Pointer<ffi.Double> a,
  int lda,
  ffi.Pointer<lapack_int> ipiv,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    ffi.Char,
    lapack_int,
    ffi.Pointer<ffi.Double>,
    lapack_int,
  )
>()
external int LAPACKE_dpotrf(
  int matrix_layout,
  int uplo,
  int n,
  ffi.Pointer<ffi.Double> a,
  int lda,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    ffi.Char,
    lapack_int,
    ffi.Pointer<ffi.Float>,
    lapack_int,
  )
>()
external int LAPACKE_spotrf(
  int matrix_layout,
  int uplo,
  int n,
  ffi.Pointer<ffi.Float> a,
  int lda,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    ffi.Char,
    lapack_int,
    ffi.Pointer<ffi.Float>,
    lapack_int,
  )
>()
external int LAPACKE_cpotrf(
  int matrix_layout,
  int uplo,
  int n,
  ffi.Pointer<ffi.Float> a,
  int lda,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    ffi.Char,
    lapack_int,
    ffi.Pointer<ffi.Double>,
    lapack_int,
  )
>()
external int LAPACKE_zpotrf(
  int matrix_layout,
  int uplo,
  int n,
  ffi.Pointer<ffi.Double> a,
  int lda,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    lapack_int,
    lapack_int,
    ffi.Pointer<ffi.Double>,
    lapack_int,
    ffi.Pointer<ffi.Double>,
  )
>()
external int LAPACKE_dgeqrf(
  int matrix_layout,
  int m,
  int n,
  ffi.Pointer<ffi.Double> a,
  int lda,
  ffi.Pointer<ffi.Double> tau,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    lapack_int,
    lapack_int,
    ffi.Pointer<ffi.Float>,
    lapack_int,
    ffi.Pointer<ffi.Float>,
  )
>()
external int LAPACKE_sgeqrf(
  int matrix_layout,
  int m,
  int n,
  ffi.Pointer<ffi.Float> a,
  int lda,
  ffi.Pointer<ffi.Float> tau,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    lapack_int,
    lapack_int,
    lapack_int,
    ffi.Pointer<ffi.Double>,
    lapack_int,
    ffi.Pointer<ffi.Double>,
  )
>()
external int LAPACKE_dorgqr(
  int matrix_layout,
  int m,
  int n,
  int k,
  ffi.Pointer<ffi.Double> a,
  int lda,
  ffi.Pointer<ffi.Double> tau,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    lapack_int,
    lapack_int,
    lapack_int,
    ffi.Pointer<ffi.Float>,
    lapack_int,
    ffi.Pointer<ffi.Float>,
  )
>()
external int LAPACKE_sorgqr(
  int matrix_layout,
  int m,
  int n,
  int k,
  ffi.Pointer<ffi.Float> a,
  int lda,
  ffi.Pointer<ffi.Float> tau,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    ffi.Char,
    ffi.Char,
    lapack_int,
    lapack_int,
    ffi.Pointer<ffi.Double>,
    lapack_int,
    ffi.Pointer<ffi.Double>,
    ffi.Pointer<ffi.Double>,
    lapack_int,
    ffi.Pointer<ffi.Double>,
    lapack_int,
    ffi.Pointer<ffi.Double>,
  )
>()
external int LAPACKE_dgesvd(
  int matrix_layout,
  int jobu,
  int jobvt,
  int m,
  int n,
  ffi.Pointer<ffi.Double> a,
  int lda,
  ffi.Pointer<ffi.Double> s,
  ffi.Pointer<ffi.Double> u,
  int ldu,
  ffi.Pointer<ffi.Double> vt,
  int ldvt,
  ffi.Pointer<ffi.Double> superb,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    ffi.Char,
    ffi.Char,
    lapack_int,
    lapack_int,
    ffi.Pointer<ffi.Float>,
    lapack_int,
    ffi.Pointer<ffi.Float>,
    ffi.Pointer<ffi.Float>,
    lapack_int,
    ffi.Pointer<ffi.Float>,
    lapack_int,
    ffi.Pointer<ffi.Float>,
  )
>()
external int LAPACKE_sgesvd(
  int matrix_layout,
  int jobu,
  int jobvt,
  int m,
  int n,
  ffi.Pointer<ffi.Float> a,
  int lda,
  ffi.Pointer<ffi.Float> s,
  ffi.Pointer<ffi.Float> u,
  int ldu,
  ffi.Pointer<ffi.Float> vt,
  int ldvt,
  ffi.Pointer<ffi.Float> superb,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    ffi.Char,
    ffi.Char,
    lapack_int,
    ffi.Pointer<ffi.Double>,
    lapack_int,
    ffi.Pointer<ffi.Double>,
    ffi.Pointer<ffi.Double>,
    ffi.Pointer<ffi.Double>,
    lapack_int,
    ffi.Pointer<ffi.Double>,
    lapack_int,
  )
>()
external int LAPACKE_dgeev(
  int matrix_layout,
  int jobvl,
  int jobvr,
  int n,
  ffi.Pointer<ffi.Double> a,
  int lda,
  ffi.Pointer<ffi.Double> wr,
  ffi.Pointer<ffi.Double> wi,
  ffi.Pointer<ffi.Double> vl,
  int ldvl,
  ffi.Pointer<ffi.Double> vr,
  int ldvr,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    ffi.Char,
    ffi.Char,
    lapack_int,
    ffi.Pointer<ffi.Float>,
    lapack_int,
    ffi.Pointer<ffi.Float>,
    ffi.Pointer<ffi.Float>,
    ffi.Pointer<ffi.Float>,
    lapack_int,
    ffi.Pointer<ffi.Float>,
    lapack_int,
  )
>()
external int LAPACKE_sgeev(
  int matrix_layout,
  int jobvl,
  int jobvr,
  int n,
  ffi.Pointer<ffi.Float> a,
  int lda,
  ffi.Pointer<ffi.Float> wr,
  ffi.Pointer<ffi.Float> wi,
  ffi.Pointer<ffi.Float> vl,
  int ldvl,
  ffi.Pointer<ffi.Float> vr,
  int ldvr,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    lapack_int,
    lapack_int,
    ffi.Pointer<ffi.Double>,
    lapack_int,
    ffi.Pointer<lapack_int>,
    ffi.Pointer<ffi.Double>,
    lapack_int,
  )
>()
external int LAPACKE_dgesv(
  int matrix_layout,
  int n,
  int nrhs,
  ffi.Pointer<ffi.Double> a,
  int lda,
  ffi.Pointer<lapack_int> ipiv,
  ffi.Pointer<ffi.Double> b,
  int ldb,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    lapack_int,
    lapack_int,
    ffi.Pointer<ffi.Float>,
    lapack_int,
    ffi.Pointer<lapack_int>,
    ffi.Pointer<ffi.Float>,
    lapack_int,
  )
>()
external int LAPACKE_sgesv(
  int matrix_layout,
  int n,
  int nrhs,
  ffi.Pointer<ffi.Float> a,
  int lda,
  ffi.Pointer<lapack_int> ipiv,
  ffi.Pointer<ffi.Float> b,
  int ldb,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    lapack_int,
    lapack_int,
    ffi.Pointer<ffi.Double>,
    lapack_int,
    ffi.Pointer<lapack_int>,
    ffi.Pointer<ffi.Double>,
    lapack_int,
  )
>()
external int LAPACKE_zgesv(
  int matrix_layout,
  int n,
  int nrhs,
  ffi.Pointer<ffi.Double> a,
  int lda,
  ffi.Pointer<lapack_int> ipiv,
  ffi.Pointer<ffi.Double> b,
  int ldb,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    lapack_int,
    lapack_int,
    ffi.Pointer<ffi.Float>,
    lapack_int,
    ffi.Pointer<lapack_int>,
    ffi.Pointer<ffi.Float>,
    lapack_int,
  )
>()
external int LAPACKE_cgesv(
  int matrix_layout,
  int n,
  int nrhs,
  ffi.Pointer<ffi.Float> a,
  int lda,
  ffi.Pointer<lapack_int> ipiv,
  ffi.Pointer<ffi.Float> b,
  int ldb,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    ffi.Char,
    ffi.Char,
    lapack_int,
    ffi.Pointer<ffi.Double>,
    lapack_int,
    ffi.Pointer<ffi.Double>,
    ffi.Pointer<ffi.Double>,
    lapack_int,
    ffi.Pointer<ffi.Double>,
    lapack_int,
  )
>()
external int LAPACKE_zgeev(
  int matrix_layout,
  int jobvl,
  int jobvr,
  int n,
  ffi.Pointer<ffi.Double> a,
  int lda,
  ffi.Pointer<ffi.Double> w,
  ffi.Pointer<ffi.Double> vl,
  int ldvl,
  ffi.Pointer<ffi.Double> vr,
  int ldvr,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    ffi.Char,
    ffi.Char,
    lapack_int,
    ffi.Pointer<ffi.Float>,
    lapack_int,
    ffi.Pointer<ffi.Float>,
    ffi.Pointer<ffi.Float>,
    lapack_int,
    ffi.Pointer<ffi.Float>,
    lapack_int,
  )
>()
external int LAPACKE_cgeev(
  int matrix_layout,
  int jobvl,
  int jobvr,
  int n,
  ffi.Pointer<ffi.Float> a,
  int lda,
  ffi.Pointer<ffi.Float> w,
  ffi.Pointer<ffi.Float> vl,
  int ldvl,
  ffi.Pointer<ffi.Float> vr,
  int ldvr,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    lapack_int,
    lapack_int,
    lapack_int,
    ffi.Pointer<ffi.Double>,
    lapack_int,
    ffi.Pointer<ffi.Double>,
    lapack_int,
    ffi.Pointer<ffi.Double>,
    ffi.Double,
    ffi.Pointer<lapack_int>,
  )
>()
external int LAPACKE_dgelsd(
  int matrix_layout,
  int m,
  int n,
  int nrhs,
  ffi.Pointer<ffi.Double> a,
  int lda,
  ffi.Pointer<ffi.Double> b,
  int ldb,
  ffi.Pointer<ffi.Double> s,
  double rcond,
  ffi.Pointer<lapack_int> rank,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    lapack_int,
    lapack_int,
    lapack_int,
    ffi.Pointer<ffi.Float>,
    lapack_int,
    ffi.Pointer<ffi.Float>,
    lapack_int,
    ffi.Pointer<ffi.Float>,
    ffi.Float,
    ffi.Pointer<lapack_int>,
  )
>()
external int LAPACKE_sgelsd(
  int matrix_layout,
  int m,
  int n,
  int nrhs,
  ffi.Pointer<ffi.Float> a,
  int lda,
  ffi.Pointer<ffi.Float> b,
  int ldb,
  ffi.Pointer<ffi.Float> s,
  double rcond,
  ffi.Pointer<lapack_int> rank,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    lapack_int,
    lapack_int,
    lapack_int,
    ffi.Pointer<ffi.Double>,
    lapack_int,
    ffi.Pointer<ffi.Double>,
    lapack_int,
    ffi.Pointer<ffi.Double>,
    ffi.Double,
    ffi.Pointer<lapack_int>,
  )
>()
external int LAPACKE_zgelsd(
  int matrix_layout,
  int m,
  int n,
  int nrhs,
  ffi.Pointer<ffi.Double> a,
  int lda,
  ffi.Pointer<ffi.Double> b,
  int ldb,
  ffi.Pointer<ffi.Double> s,
  double rcond,
  ffi.Pointer<lapack_int> rank,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    lapack_int,
    lapack_int,
    lapack_int,
    ffi.Pointer<ffi.Float>,
    lapack_int,
    ffi.Pointer<ffi.Float>,
    lapack_int,
    ffi.Pointer<ffi.Float>,
    ffi.Float,
    ffi.Pointer<lapack_int>,
  )
>()
external int LAPACKE_cgelsd(
  int matrix_layout,
  int m,
  int n,
  int nrhs,
  ffi.Pointer<ffi.Float> a,
  int lda,
  ffi.Pointer<ffi.Float> b,
  int ldb,
  ffi.Pointer<ffi.Float> s,
  double rcond,
  ffi.Pointer<lapack_int> rank,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    lapack_int,
    lapack_int,
    ffi.Pointer<ffi.Double>,
    lapack_int,
    ffi.Pointer<ffi.Double>,
  )
>()
external int LAPACKE_zgeqrf(
  int matrix_layout,
  int m,
  int n,
  ffi.Pointer<ffi.Double> a,
  int lda,
  ffi.Pointer<ffi.Double> tau,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    lapack_int,
    lapack_int,
    ffi.Pointer<ffi.Float>,
    lapack_int,
    ffi.Pointer<ffi.Float>,
  )
>()
external int LAPACKE_cgeqrf(
  int matrix_layout,
  int m,
  int n,
  ffi.Pointer<ffi.Float> a,
  int lda,
  ffi.Pointer<ffi.Float> tau,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    lapack_int,
    lapack_int,
    lapack_int,
    ffi.Pointer<ffi.Double>,
    lapack_int,
    ffi.Pointer<ffi.Double>,
  )
>()
external int LAPACKE_zungqr(
  int matrix_layout,
  int m,
  int n,
  int k,
  ffi.Pointer<ffi.Double> a,
  int lda,
  ffi.Pointer<ffi.Double> tau,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    lapack_int,
    lapack_int,
    lapack_int,
    ffi.Pointer<ffi.Float>,
    lapack_int,
    ffi.Pointer<ffi.Float>,
  )
>()
external int LAPACKE_cungqr(
  int matrix_layout,
  int m,
  int n,
  int k,
  ffi.Pointer<ffi.Float> a,
  int lda,
  ffi.Pointer<ffi.Float> tau,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    ffi.Char,
    ffi.Char,
    lapack_int,
    lapack_int,
    ffi.Pointer<ffi.Double>,
    lapack_int,
    ffi.Pointer<ffi.Double>,
    ffi.Pointer<ffi.Double>,
    lapack_int,
    ffi.Pointer<ffi.Double>,
    lapack_int,
    ffi.Pointer<ffi.Double>,
  )
>()
external int LAPACKE_zgesvd(
  int matrix_layout,
  int jobu,
  int jobvt,
  int m,
  int n,
  ffi.Pointer<ffi.Double> a,
  int lda,
  ffi.Pointer<ffi.Double> s,
  ffi.Pointer<ffi.Double> u,
  int ldu,
  ffi.Pointer<ffi.Double> vt,
  int ldvt,
  ffi.Pointer<ffi.Double> superb,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    ffi.Char,
    ffi.Char,
    lapack_int,
    lapack_int,
    ffi.Pointer<ffi.Float>,
    lapack_int,
    ffi.Pointer<ffi.Float>,
    ffi.Pointer<ffi.Float>,
    lapack_int,
    ffi.Pointer<ffi.Float>,
    lapack_int,
    ffi.Pointer<ffi.Float>,
  )
>()
external int LAPACKE_cgesvd(
  int matrix_layout,
  int jobu,
  int jobvt,
  int m,
  int n,
  ffi.Pointer<ffi.Float> a,
  int lda,
  ffi.Pointer<ffi.Float> s,
  ffi.Pointer<ffi.Float> u,
  int ldu,
  ffi.Pointer<ffi.Float> vt,
  int ldvt,
  ffi.Pointer<ffi.Float> superb,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    ffi.Char,
    ffi.Char,
    LAPACK_D_SELECT2,
    lapack_int,
    ffi.Pointer<ffi.Double>,
    lapack_int,
    ffi.Pointer<lapack_int>,
    ffi.Pointer<ffi.Double>,
    ffi.Pointer<ffi.Double>,
    ffi.Pointer<ffi.Double>,
    lapack_int,
  )
>()
external int LAPACKE_dgees(
  int matrix_layout,
  int jobvs,
  int sort,
  LAPACK_D_SELECT2 select,
  int n,
  ffi.Pointer<ffi.Double> a,
  int lda,
  ffi.Pointer<lapack_int> sdim,
  ffi.Pointer<ffi.Double> wr,
  ffi.Pointer<ffi.Double> wi,
  ffi.Pointer<ffi.Double> vs,
  int ldvs,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    ffi.Char,
    ffi.Char,
    LAPACK_S_SELECT2,
    lapack_int,
    ffi.Pointer<ffi.Float>,
    lapack_int,
    ffi.Pointer<lapack_int>,
    ffi.Pointer<ffi.Float>,
    ffi.Pointer<ffi.Float>,
    ffi.Pointer<ffi.Float>,
    lapack_int,
  )
>()
external int LAPACKE_sgees(
  int matrix_layout,
  int jobvs,
  int sort,
  LAPACK_S_SELECT2 select,
  int n,
  ffi.Pointer<ffi.Float> a,
  int lda,
  ffi.Pointer<lapack_int> sdim,
  ffi.Pointer<ffi.Float> wr,
  ffi.Pointer<ffi.Float> wi,
  ffi.Pointer<ffi.Float> vs,
  int ldvs,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    ffi.Char,
    ffi.Char,
    LAPACK_C_SELECT1,
    lapack_int,
    ffi.Pointer<ffi.Float>,
    lapack_int,
    ffi.Pointer<lapack_int>,
    ffi.Pointer<ffi.Float>,
    ffi.Pointer<ffi.Float>,
    lapack_int,
  )
>()
external int LAPACKE_cgees(
  int matrix_layout,
  int jobvs,
  int sort,
  LAPACK_C_SELECT1 select,
  int n,
  ffi.Pointer<ffi.Float> a,
  int lda,
  ffi.Pointer<lapack_int> sdim,
  ffi.Pointer<ffi.Float> w,
  ffi.Pointer<ffi.Float> vs,
  int ldvs,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    ffi.Char,
    ffi.Char,
    LAPACK_Z_SELECT1,
    lapack_int,
    ffi.Pointer<ffi.Double>,
    lapack_int,
    ffi.Pointer<lapack_int>,
    ffi.Pointer<ffi.Double>,
    ffi.Pointer<ffi.Double>,
    lapack_int,
  )
>()
external int LAPACKE_zgees(
  int matrix_layout,
  int jobvs,
  int sort,
  LAPACK_Z_SELECT1 select,
  int n,
  ffi.Pointer<ffi.Double> a,
  int lda,
  ffi.Pointer<lapack_int> sdim,
  ffi.Pointer<ffi.Double> w,
  ffi.Pointer<ffi.Double> vs,
  int ldvs,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    lapack_int,
    lapack_int,
    lapack_int,
    ffi.Pointer<ffi.Double>,
    lapack_int,
    ffi.Pointer<ffi.Double>,
  )
>()
external int LAPACKE_dgehrd(
  int matrix_layout,
  int n,
  int ilo,
  int ihi,
  ffi.Pointer<ffi.Double> a,
  int lda,
  ffi.Pointer<ffi.Double> tau,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    lapack_int,
    lapack_int,
    lapack_int,
    ffi.Pointer<ffi.Float>,
    lapack_int,
    ffi.Pointer<ffi.Float>,
  )
>()
external int LAPACKE_sgehrd(
  int matrix_layout,
  int n,
  int ilo,
  int ihi,
  ffi.Pointer<ffi.Float> a,
  int lda,
  ffi.Pointer<ffi.Float> tau,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    lapack_int,
    lapack_int,
    lapack_int,
    ffi.Pointer<ffi.Double>,
    lapack_int,
    ffi.Pointer<ffi.Double>,
  )
>()
external int LAPACKE_zgehrd(
  int matrix_layout,
  int n,
  int ilo,
  int ihi,
  ffi.Pointer<ffi.Double> a,
  int lda,
  ffi.Pointer<ffi.Double> tau,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    lapack_int,
    lapack_int,
    lapack_int,
    ffi.Pointer<ffi.Float>,
    lapack_int,
    ffi.Pointer<ffi.Float>,
  )
>()
external int LAPACKE_cgehrd(
  int matrix_layout,
  int n,
  int ilo,
  int ihi,
  ffi.Pointer<ffi.Float> a,
  int lda,
  ffi.Pointer<ffi.Float> tau,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    lapack_int,
    lapack_int,
    lapack_int,
    ffi.Pointer<ffi.Double>,
    lapack_int,
    ffi.Pointer<ffi.Double>,
  )
>()
external int LAPACKE_dorghr(
  int matrix_layout,
  int n,
  int ilo,
  int ihi,
  ffi.Pointer<ffi.Double> a,
  int lda,
  ffi.Pointer<ffi.Double> tau,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    lapack_int,
    lapack_int,
    lapack_int,
    ffi.Pointer<ffi.Float>,
    lapack_int,
    ffi.Pointer<ffi.Float>,
  )
>()
external int LAPACKE_sorghr(
  int matrix_layout,
  int n,
  int ilo,
  int ihi,
  ffi.Pointer<ffi.Float> a,
  int lda,
  ffi.Pointer<ffi.Float> tau,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    lapack_int,
    lapack_int,
    lapack_int,
    ffi.Pointer<ffi.Double>,
    lapack_int,
    ffi.Pointer<ffi.Double>,
  )
>()
external int LAPACKE_zunghr(
  int matrix_layout,
  int n,
  int ilo,
  int ihi,
  ffi.Pointer<ffi.Double> a,
  int lda,
  ffi.Pointer<ffi.Double> tau,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    lapack_int,
    lapack_int,
    lapack_int,
    ffi.Pointer<ffi.Float>,
    lapack_int,
    ffi.Pointer<ffi.Float>,
  )
>()
external int LAPACKE_cunghr(
  int matrix_layout,
  int n,
  int ilo,
  int ihi,
  ffi.Pointer<ffi.Float> a,
  int lda,
  ffi.Pointer<ffi.Float> tau,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    ffi.Char,
    ffi.Char,
    lapack_int,
    ffi.Pointer<ffi.Double>,
    lapack_int,
    ffi.Pointer<ffi.Double>,
  )
>()
external int LAPACKE_dsyev(
  int matrix_layout,
  int jobz,
  int uplo,
  int n,
  ffi.Pointer<ffi.Double> a,
  int lda,
  ffi.Pointer<ffi.Double> w,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    ffi.Char,
    ffi.Char,
    lapack_int,
    ffi.Pointer<ffi.Double>,
    lapack_int,
    ffi.Pointer<ffi.Double>,
  )
>()
external int LAPACKE_dsyevd(
  int matrix_layout,
  int jobz,
  int uplo,
  int n,
  ffi.Pointer<ffi.Double> a,
  int lda,
  ffi.Pointer<ffi.Double> w,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    ffi.Char,
    ffi.Char,
    lapack_int,
    ffi.Pointer<ffi.Float>,
    lapack_int,
    ffi.Pointer<ffi.Float>,
  )
>()
external int LAPACKE_ssyev(
  int matrix_layout,
  int jobz,
  int uplo,
  int n,
  ffi.Pointer<ffi.Float> a,
  int lda,
  ffi.Pointer<ffi.Float> w,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    ffi.Char,
    ffi.Char,
    lapack_int,
    ffi.Pointer<ffi.Float>,
    lapack_int,
    ffi.Pointer<ffi.Float>,
  )
>()
external int LAPACKE_ssyevd(
  int matrix_layout,
  int jobz,
  int uplo,
  int n,
  ffi.Pointer<ffi.Float> a,
  int lda,
  ffi.Pointer<ffi.Float> w,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    ffi.Char,
    ffi.Char,
    lapack_int,
    ffi.Pointer<ffi.Double>,
    lapack_int,
    ffi.Pointer<ffi.Double>,
  )
>()
external int LAPACKE_zheev(
  int matrix_layout,
  int jobz,
  int uplo,
  int n,
  ffi.Pointer<ffi.Double> a,
  int lda,
  ffi.Pointer<ffi.Double> w,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    ffi.Char,
    ffi.Char,
    lapack_int,
    ffi.Pointer<ffi.Double>,
    lapack_int,
    ffi.Pointer<ffi.Double>,
  )
>()
external int LAPACKE_zheevd(
  int matrix_layout,
  int jobz,
  int uplo,
  int n,
  ffi.Pointer<ffi.Double> a,
  int lda,
  ffi.Pointer<ffi.Double> w,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    ffi.Char,
    ffi.Char,
    lapack_int,
    ffi.Pointer<ffi.Float>,
    lapack_int,
    ffi.Pointer<ffi.Float>,
  )
>()
external int LAPACKE_cheev(
  int matrix_layout,
  int jobz,
  int uplo,
  int n,
  ffi.Pointer<ffi.Float> a,
  int lda,
  ffi.Pointer<ffi.Float> w,
);

@ffi.Native<
  lapack_int Function(
    ffi.Int,
    ffi.Char,
    ffi.Char,
    lapack_int,
    ffi.Pointer<ffi.Float>,
    lapack_int,
    ffi.Pointer<ffi.Float>,
  )
>()
external int LAPACKE_cheevd(
  int matrix_layout,
  int jobz,
  int uplo,
  int n,
  ffi.Pointer<ffi.Float> a,
  int lda,
  ffi.Pointer<ffi.Float> w,
);

typedef blasint = ffi.Int;
typedef Dartblasint = int;
typedef lapack_int = ffi.Int;
typedef Dartlapack_int = int;

typedef LAPACK_D_SELECT2Function =
    ffi.Int Function(ffi.Pointer<ffi.Double>, ffi.Pointer<ffi.Double>);
typedef DartLAPACK_D_SELECT2Function =
    int Function(ffi.Pointer<ffi.Double>, ffi.Pointer<ffi.Double>);
typedef LAPACK_D_SELECT2 =
    ffi.Pointer<ffi.NativeFunction<LAPACK_D_SELECT2Function>>;
typedef LAPACK_S_SELECT2Function =
    ffi.Int Function(ffi.Pointer<ffi.Float>, ffi.Pointer<ffi.Float>);
typedef DartLAPACK_S_SELECT2Function =
    int Function(ffi.Pointer<ffi.Float>, ffi.Pointer<ffi.Float>);
typedef LAPACK_S_SELECT2 =
    ffi.Pointer<ffi.NativeFunction<LAPACK_S_SELECT2Function>>;
typedef LAPACK_C_SELECT1Function = ffi.Int Function(ffi.Pointer<ffi.Float>);
typedef DartLAPACK_C_SELECT1Function = int Function(ffi.Pointer<ffi.Float>);
typedef LAPACK_C_SELECT1 =
    ffi.Pointer<ffi.NativeFunction<LAPACK_C_SELECT1Function>>;
typedef LAPACK_Z_SELECT1Function = ffi.Int Function(ffi.Pointer<ffi.Double>);
typedef DartLAPACK_Z_SELECT1Function = int Function(ffi.Pointer<ffi.Double>);
typedef LAPACK_Z_SELECT1 =
    ffi.Pointer<ffi.NativeFunction<LAPACK_Z_SELECT1Function>>;
