// THIS FILE IS AUTOGENERATED BY `tool/regenerate_hashes.dart`. TO UPDATE, RUN:
//
//   dart tool/regenerate_hashes.dart <github release tag>
//

import 'package:code_assets/code_assets.dart';

/// Upstream release tag for `gfx-rs/wgpu-native`.
const wgpuVersion = 'v29.0.1.1';

/// Upstream base URL for `wgpu-native` releases.
const wgpuBaseUrl =
    'https://github.com/gfx-rs/wgpu-native/releases/download/$wgpuVersion';

/// Asset descriptor for a `wgpu-native` platform binary archive.
final class WgpuAssetConfig {
  /// Archive filename on GitHub Releases.
  final String zipName;

  /// Expected SHA-256 digest of the `.zip` archive.
  final String sha256;

  /// Extracted dynamic library filename.
  final String libName;

  /// Creates a [WgpuAssetConfig].
  const WgpuAssetConfig({
    required this.zipName,
    required this.sha256,
    required this.libName,
  });
}

/// Pinned SHA-256 digests for `wgpu-native` archives indexed by `(OS, Architecture)`.
const fileHashes = <(OS, Architecture), WgpuAssetConfig>{
  (OS.linux, Architecture.x64): WgpuAssetConfig(
    zipName: 'wgpu-linux-x86_64-release.zip',
    sha256: '95a4d90c071005a98d03eab348beaa6b07e16eb00d1dcdb9f8348f75eb97ec5a',
    libName: 'libwgpu_native.so',
  ),
  (OS.linux, Architecture.arm64): WgpuAssetConfig(
    zipName: 'wgpu-linux-aarch64-release.zip',
    sha256: '015fcdf1dbae82e614a783cc38017e5399ae0927a889fe9b69c9b664bc61b47a',
    libName: 'libwgpu_native.so',
  ),
  (OS.macOS, Architecture.arm64): WgpuAssetConfig(
    zipName: 'wgpu-macos-aarch64-release.zip',
    sha256: 'a5797a37b1adf720bcd5dcffb291edbbd5b7b14be0a3874c28e6393a655a7a3e',
    libName: 'libwgpu_native.dylib',
  ),
  (OS.macOS, Architecture.x64): WgpuAssetConfig(
    zipName: 'wgpu-macos-x86_64-release.zip',
    sha256: '8e2f7378548ddd0e2cf21e7d864dda46e953f0af724855a33778b85ead206d41',
    libName: 'libwgpu_native.dylib',
  ),
  (OS.windows, Architecture.x64): WgpuAssetConfig(
    zipName: 'wgpu-windows-x86_64-msvc-release.zip',
    sha256: '7e67d7445c42aeb85e30f88930fd8d7d83ee769e3390aeb1ada75ebf3cf78132',
    libName: 'wgpu_native.dll',
  ),
  (OS.windows, Architecture.arm64): WgpuAssetConfig(
    zipName: 'wgpu-windows-aarch64-msvc-release.zip',
    sha256: '4a876421a8c1e5fe72f849b3722214280fe485cb1c56f77f8b0c82414be5b29f',
    libName: 'wgpu_native.dll',
  ),
  (OS.windows, Architecture.ia32): WgpuAssetConfig(
    zipName: 'wgpu-windows-i686-msvc-release.zip',
    sha256: 'ad59d4eadfcfe667999a37e096cc551ecf3f56c387b5a7fd5f61baebf105f54a',
    libName: 'wgpu_native.dll',
  ),
  (OS.android, Architecture.arm64): WgpuAssetConfig(
    zipName: 'wgpu-android-aarch64-release.zip',
    sha256: '721741f1b05a20c1738166bedf7a5efb2ba4b382da689526d3fc33de22bdd573',
    libName: 'libwgpu_native.so',
  ),
  (OS.android, Architecture.arm): WgpuAssetConfig(
    zipName: 'wgpu-android-armv7-release.zip',
    sha256: 'f9d76c77b3fda3f7121476884eb16ec067f7dada83276298a3cc8bf6a8403d60',
    libName: 'libwgpu_native.so',
  ),
  (OS.android, Architecture.x64): WgpuAssetConfig(
    zipName: 'wgpu-android-x86_64-release.zip',
    sha256: 'ef16fc0644bf0e308a39ac4516742da8e22d8c201d3a542cc5baf533d272c491',
    libName: 'libwgpu_native.so',
  ),
  (OS.android, Architecture.ia32): WgpuAssetConfig(
    zipName: 'wgpu-android-i686-release.zip',
    sha256: '593b94875bc4fcc1506ea0b6714dd12b96b7c852921caa63f45eb61517793312',
    libName: 'libwgpu_native.so',
  ),
  (OS.iOS, Architecture.arm64): WgpuAssetConfig(
    zipName: 'wgpu-ios-aarch64-release.zip',
    sha256: 'e36c9913b9e5095a530fa9121c50b16a4e3dd020e1eebf601f2f47ce24d56941',
    libName: 'libwgpu_native.dylib',
  ),
  (OS.iOS, Architecture.x64): WgpuAssetConfig(
    zipName: 'wgpu-ios-x86_64-simulator-release.zip',
    sha256: '94f67e1b268e8dd31b8e59b32f211ac469f09ed7950fceee52bd84f0623da3d9',
    libName: 'libwgpu_native.dylib',
  ),
};
