name: pocketfft
description: Native AOT FFI bindings for high-performance mixed-radix Fast Fourier Transforms.
version: 0.0.1
resolution: workspace
repository: https://github.com/sigurdm/math

environment:
  sdk: ^3.11.5

dependencies:
  ffi: ^2.2.0
  hooks: ^1.0.3
  code_assets: ^1.0.0
  archive: ^3.6.1

dev_dependencies:
  lints: ^6.1.0
  test: ^1.31.1
  ffigen: ^20.1.1
